import { createHash } from 'node:crypto';
import { readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { z } from 'zod';
import { defineCapability } from '@jarvis/capability-sdk';
const within = (root: string, file: string) => { const r = resolve(root); const f = resolve(file); if (f !== r && !f.startsWith(`${r}\\`) && !f.startsWith(`${r}/`)) throw new Error('path outside credential scope'); return f; };
export default defineCapability({ id: 'capabilities.filesystem', version: '1.0.0', description: 'Scoped filesystem reads and atomic writes', provider: 'filesystem', executionEnvironment: 'worker', auditPolicy: { hashInput: true, recordOutput: 'summary' }, privacyRequirements: { maxContentPrivacyClass: 'SENSITIVE' }, actions: {
  read_file: { input: z.object({ root: z.string(), path: z.string() }), output: z.object({ content: z.string(), sha256: z.string() }), risk: 'LOW', reversible: false, idempotent: true, requiredScopes: ['filesystem.read'], approvalPolicy: 'default', timeoutMs: 5000, verificationStrategy: { kind: 'hash-match', ofPath: 'path', expectPath: 'sha256' }, sideEffects: [], async execute(_ctx, input) { const content = await readFile(within(input.root, input.path), 'utf8'); return { content, sha256: createHash('sha256').update(content).digest('hex') }; }, async verify(_ctx, input, output) { const current = await readFile(within(input.root, input.path), 'utf8'); return { verified: createHash('sha256').update(current).digest('hex') === output.sha256, checks: [{ name: 'hash', ok: true, detail: 'world reread' }] }; } },
  write_file: { input: z.object({ root: z.string(), path: z.string(), content: z.string() }), output: z.object({ sha256: z.string() }), risk: 'MEDIUM', reversible: true, idempotent: true, requiredScopes: ['filesystem.write'], approvalPolicy: 'default', timeoutMs: 5000, verificationStrategy: { kind: 'hash-match', ofPath: 'path', expectPath: 'sha256' }, rollbackStrategy: { kind: 'restore-snapshot', capturedBy: 'read_file', restoreRef: 'rollback' }, sideEffects: ['write file'], async execute(_ctx, input) { const target = within(input.root, input.path); const temp = `${target}.${process.pid}.tmp`; await writeFile(temp, input.content); await rename(temp, target); return { sha256: createHash('sha256').update(input.content).digest('hex') }; }, async verify(_ctx, input, output) { const content = await readFile(within(input.root, input.path), 'utf8'); const ok = createHash('sha256').update(content).digest('hex') === output.sha256; return { verified: ok, checks: [{ name: 'hash', ok, detail: 'world reread' }] }; }, async rollback(_ctx, input, before) { const prior = typeof before === 'string' ? before : ''; await writeFile(within(input.root, input.path), prior); return { undone: true, residual: [] }; } },
} });
