import{describe,expect,it,vi}from'vitest';import type{ModelRegistration,ModelRequest}from'@jarvis/contracts';import{ModelGateway}from'./gateway.ts';import{ModelRegistry}from'./registry.ts';import type{ProviderAdapter}from'./provider.ts';import{OpenAIAdapter}from'./adapters/openai.ts';import{AnthropicAdapter}from'./adapters/anthropic.ts';import{OpenAICompatibleAdapter}from'./adapters/openai-compatible.ts';
const request=(p:Partial<ModelRequest>={}):ModelRequest=>({task:'reason',capabilities:['json'],input:{instruction:'x',context:{}as never,constraints:[]},budget:{contextUnits:10,maxOutput:10},locality:'any',cloudAllowed:true,correlationId:'c',principalId:'p',...p});
const model=(id:string,provider:string,locality:ModelRegistration['locality']='cloud-ok',cost=.001):ModelRegistration=>({id,provider,displayName:id,tasks:['reason'],capabilities:['json'],contextLimitUnits:100,costPerContextUnit:cost,costPerOutputUnit:cost,locality,enabled:true,registeredAt:new Date().toISOString()});
const good=(provider:string):ProviderAdapter=>({provider,async generate(m,r){return{modelId:m.id,output:{proposals:[]},usage:{contextUnits:1,outputUnits:1,costEstimate:0,latencyMs:1},finishReason:'stop',provenance:{method:'model',producedBy:m.id,producedOn:'test',producedAt:new Date().toISOString(),correlationId:r.correlationId,derivedFromUntrusted:true}}},async health(m){return{modelId:m.id,provider,status:'healthy',checkedAt:new Date().toISOString()}}});
describe('gateway failure behavior',()=>{
 it.each([['OpenAI',(f:typeof fetch)=>new OpenAIAdapter('key','http://provider',f)],['Anthropic',(f:typeof fetch)=>new AnthropicAdapter('key','http://provider',f)],['local',(f:typeof fetch)=>new OpenAICompatibleAdapter('local','http://provider','',f)]])('%s reports provider outage',async(_name,make)=>{const adapter=make(vi.fn(async()=>new Response('down',{status:503})));await expect(adapter.generate(model('m',adapter.provider),request(),AbortSignal.timeout(1000))).rejects.toMatchObject({code:'UNAVAILABLE'})});
 it('classifies rate limiting',async()=>{const a=new OpenAIAdapter('key','http://provider',vi.fn(async()=>new Response('slow down',{status:429})));await expect(a.generate(model('m','openai'),request(),AbortSignal.timeout(1000))).rejects.toMatchObject({code:'RATE_LIMITED'})});
 it('falls back to a second eligible provider',async()=>{const r=new ModelRegistry(),bad={...good('one'),async generate(){throw new Error('offline')}};r.register(model('first','one'),bad);r.register(model('second','two'),good('two'));const response=await new ModelGateway(r).generate(request());expect(response.modelId).toBe('second');expect(response.routing).toMatchObject({selectedModelId:'second',fallbackReason:'first failed before selection'});expect(response.routing?.candidates.find(candidate=>candidate.modelId==='first')?.state).toBe('FAILED')});
 it('denies cloud when permission is absent',()=>{const r=new ModelRegistry();r.register(model('cloud','one'),good('one'));expect(()=>r.candidates(request({cloudAllowed:false}))).not.toThrow();expect(r.candidates(request({cloudAllowed:false}))).toEqual([])});
 it('reports budget exhaustion distinctly',async()=>{const r=new ModelRegistry();r.register(model('expensive','one','cloud-ok',1),good('one'));await expect(new ModelGateway(r).generate(request({budget:{contextUnits:10,maxOutput:10,maxCost:1}}))).rejects.toMatchObject({code:'BUDGET_EXCEEDED'})});
 it('cancels timed out calls',async()=>{const r=new ModelRegistry();const slow:ProviderAdapter={...good('slow'),generate:async(_m,_r,signal)=>await new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(new Error('aborted'))))};r.register(model('slow','slow'),slow);await expect(new ModelGateway(r).generate(request({budget:{contextUnits:1,maxOutput:1,maxLatencyMs:5}}))).rejects.toMatchObject({code:'TIMEOUT'})});
});
