import { z } from 'zod'; import type { AgentManifest, AgentResult, ModelRequest, ModelResponse, Proposal } from '@jarvis/contracts'; import type { ModelGatewayPort } from './model-client.ts';
const provenance=z.object({method:z.enum(['sensor','model','retrieval','inference','assertion','derivation','system']),producedBy:z.string(),producedOn:z.string(),producedAt:z.string().datetime(),correlationId:z.string(),derivedFromUntrusted:z.boolean(),sourceRefs:z.array(z.string()).optional(),model:z.object({id:z.string(),version:z.string()}).optional()});
const base={proposalId:z.string().min(1),correlationId:z.string().min(1),confidence:z.number().min(0).max(1),provenance};
const proposal=z.discriminatedUnion('kind',[z.object({...base,kind:z.literal('answer'),text:z.string(),citations:z.array(z.string())}),z.object({...base,kind:z.literal('clarification_request'),question:z.string(),options:z.array(z.string()).optional()}),z.object({...base,kind:z.literal('capability_invocation'),invocation:z.object({capabilityId:z.string(),capabilityVersion:z.string(),action:z.string(),input:z.unknown()}),justification:z.string()}),z.object({...base,kind:z.literal('plan'),goal:z.string(),steps:z.array(z.unknown())}),z.object({...base,kind:z.literal('draft'),artifact:z.string(),mimeType:z.string()}),z.object({...base,kind:z.literal('fact_extraction'),candidates:z.array(z.unknown())}),z.object({...base,kind:z.literal('policy_recommendation'),recommendation:z.enum(['ALLOW','DENY','REQUIRE_APPROVAL']),reasoning:z.string()}),z.object({...base,kind:z.literal('capability_draft'),manifest:z.unknown(),adapterSource:z.string(),testSource:z.string(),researchNotes:z.string(),declaredEgress:z.array(z.string())})]);
export const AGENTS:Record<string,AgentManifest>={
 'agents.oracle':{id:'agents.oracle',version:'0.42.0',displayName:'Oracle',role:'General reasoning and planning',leasePolicy:{maxWallTimeMs:120000,maxContextUnits:200000,maxCostUnits:50},proposalScope:{kinds:['answer','plan','clarification_request','fact_extraction'],capabilities:[]},modelHints:{tasks:['reason'],locality:'any'}},
 'agents.scout':{id:'agents.scout',version:'0.42.0',displayName:'Scout',role:'Research and information gathering',leasePolicy:{maxWallTimeMs:600000,maxContextUnits:300000,maxCostUnits:120},proposalScope:{kinds:['answer','draft','fact_extraction','clarification_request','capability_invocation'],capabilities:['capabilities.web','capabilities.browser']},modelHints:{tasks:['reason','summarize','extract'],locality:'any'}},
 'agents.forge':{id:'agents.forge',version:'0.47.0',displayName:'Forge',role:'Engineering and code-task proposals',leasePolicy:{maxWallTimeMs:900000,maxContextUnits:400000,maxCostUnits:200},proposalScope:{kinds:['capability_draft','capability_invocation','plan','clarification_request'],capabilities:['capabilities.filesystem','capabilities.terminal']},modelHints:{tasks:['code','reason','plan'],locality:'prefer-local'}}};
export class AgentRuntime { constructor(private readonly gateway:ModelGatewayPort,private readonly now:()=>string){} async invoke(agentId:string,request:ModelRequest):Promise<{result:AgentResult;response:ModelResponse}>{const manifest=AGENTS[agentId];if(!manifest)throw new Error('unknown agent');if(!manifest.modelHints.tasks.includes(request.task))throw new Error('task outside agent manifest');request.budget.contextUnits=Math.min(request.budget.contextUnits,manifest.leasePolicy.maxContextUnits);request.budget.maxCost=Math.min(request.budget.maxCost??manifest.leasePolicy.maxCostUnits,manifest.leasePolicy.maxCostUnits);request.budget.maxLatencyMs=Math.min(request.budget.maxLatencyMs??manifest.leasePolicy.maxWallTimeMs,manifest.leasePolicy.maxWallTimeMs);const started=this.now();const response=await this.gateway.generate(request);const raw=(response.output as {proposals?:unknown})?.proposals??response.output;const parsed=z.array(proposal).safeParse(raw);if(!parsed.success)throw new Error(`invalid structured model output: ${parsed.error.issues[0]?.message??'invalid proposals'}`);for(const p of parsed.data){if(!manifest.proposalScope.kinds.includes(p.kind))throw new Error(`proposal kind ${p.kind} outside agent scope`);if(p.kind==='capability_invocation'&&!manifest.proposalScope.capabilities.includes(p.invocation.capabilityId))throw new Error('capability outside agent scope');}return{response,result:{jobId:request.correlationId,agentId,principalId:request.principalId,correlationId:request.correlationId,status:'completed',proposals:parsed.data as Proposal[],evidence:[],startedAt:started,finishedAt:this.now()}}}}
