import {describe,expect,it} from 'vitest';
import {PerceptionContext} from './perception-context.ts';
import {visionCommandSchema} from './signal-schema.ts';
import type {CapabilityInvocationProposal,InvocationResult,VisionEventCommand} from '@jarvis/contracts';
const start=Date.parse('2026-10-02T12:00:00Z');
const command=(signal:VisionEventCommand['signal']):VisionEventCommand=>({commandId:'c',nodeId:'n',principalId:'p',signal});
const screen=(at=new Date(start).toISOString())=>command({type:'screen-context',context:{source:'windows',coordinateSpace:'physical-pixels',monitors:[{id:'primary',label:'primary',x:0,y:0,width:1920,height:1080,primary:true,scaleFactor:1}],activeWindow:{application:'terminal',title:'error',windowId:'123',bounds:{x:0,y:0,width:900,height:600}},cursor:{x:100,y:100},observedAt:at}});
const proposal={invocation:{capabilityId:'capabilities.windows',action:'capture_region',input:{x:0,y:0,width:300,height:200,extractText:true}}} as CapabilityInvocationProposal;
const result={outcome:'verified',invocationId:'capture-1',output:{selectedText:'TS2304: Cannot find name widget',imageSha256:'a'.repeat(64)}} as InvocationResult;
describe('perception authority boundary',()=>{
 it('asks before reading unselected application pixels',async()=>{const service=new PerceptionContext(()=>start);service.observe(screen());const response=await service.resolve("what is wrong with that?",'p','n');expect(response.clarification).toContain('approve capture_region');expect(response.perceptionRef).toBeUndefined();});
 it('composes selected text, voice and application only after verified capture and binds ownership',async()=>{let now=start;const service=new PerceptionContext(()=>now);service.observe(screen());await service.capture(proposal,result,'p','n');const response=await service.resolve("what is wrong with that?",'p','n');expect(response.perceptionRef).toBeTruthy();const items=service.items(response.perceptionRef!,'p');expect(items.map(i=>i.kind)).toEqual(expect.arrayContaining(['conversation_turn','active_application','selected_object']));expect(items.find(i=>i.privacyClass==='RESTRICTED')?.content).toMatchObject({text:'TS2304: Cannot find name widget'});expect(()=>service.items(response.perceptionRef!,'other')).toThrow();expect((await service.resolve('repair that','p','n')).clarification).toContain('screenshot is not a repair target');now+=15001;expect(()=>service.items(response.perceptionRef!,'p')).toThrow();expect(service.focus('p')).toBeUndefined();});
 it('rejects unverified capture, stale screen and a different node',async()=>{const service=new PerceptionContext(()=>start);service.observe(screen(new Date(start-10000).toISOString()));await service.capture(proposal,{...result,outcome:'rejected'} as InvocationResult,'p','n');expect((await service.resolve('what is that','p','n')).clarification).toBeTruthy();await service.capture(proposal,result,'p','n');expect((await service.resolve('what is that','p','other')).perceptionRef).toBeUndefined();});
 it('accepts only structured derived signals and rejects hidden raw material or malformed coordinates',()=>{const valid=screen();expect(visionCommandSchema.safeParse(valid).success).toBe(true);expect(visionCommandSchema.safeParse({...valid,signal:{...valid.signal,pixels:[1]}}).success).toBe(false);const bad=structuredClone(valid);if(bad.signal.type==='screen-context')bad.signal.context.monitors[0]!.width=-1;expect(visionCommandSchema.safeParse(bad).success).toBe(false);expect(visionCommandSchema.safeParse(command({type:'camera.restored',observedAt:'invalid'})).success).toBe(false);});
});
