import {z} from 'zod';
const text=z.string().min(1).max(1024),at=z.string().datetime({offset:true}),confidence=z.number().finite().min(0).max(1),coordinate=z.number().finite().min(-65536).max(65536);
const point=z.object({x:coordinate,y:coordinate}).strict(),bounds=z.object({x:coordinate,y:coordinate,width:z.number().positive().max(32768),height:z.number().positive().max(32768)}).strict();
const diagnostics=z.object({status:z.enum(['starting','ready','degraded','offline']),cameraId:text.optional(),cameraLabel:text.optional(),fps:z.number().min(0).max(240),inferenceLatencyMs:z.number().min(0).max(60000),airTouchLatencyMs:z.number().min(0).max(60000),confidence,currentTarget:text.optional(),droppedFrames:z.number().int().nonnegative(),calibrationQuality:confidence,model:text,updatedAt:at}).strict();
const context=z.object({source:z.enum(['windows','browser']).optional(),coordinateSpace:z.enum(['physical-pixels','css-pixels']).optional(),monitors:z.array(bounds.extend({id:text,label:text,scaleFactor:z.number().positive().max(8),primary:z.boolean()})).max(16),activeMonitorId:text.optional(),activeWindow:z.object({title:z.string().max(1024),application:text,processId:z.number().int().nonnegative().optional(),windowId:text.optional(),executable:text.optional(),bounds:bounds.optional()}).strict().optional(),scene:z.object({focusedId:text.optional(),selectedIds:z.array(text).max(32),observedAt:at}).strict().optional(),workspace:z.object({rootPath:text,repositoryRoot:text.optional(),source:z.literal('explicit-process-binding'),processId:z.number().int().positive()}).strict().optional(),cursor:point.optional(),selection:bounds.extend({monitorId:text}).optional(),observedAt:at}).strict();
export const visionCommandSchema=z.object({commandId:text,nodeId:text,principalId:text,signal:z.union([
 z.object({type:z.literal('air-touch'),frame:z.object({phase:z.enum(['hover','pinch-start','pinch-move','pinch-end','swipe','open-palm','lost']),monitorId:text,point:point.optional(),direction:z.enum(['left','right','up','down']).optional(),confidence,observedAt:at,sequence:z.number().int().nonnegative().optional(),latencyMs:z.number().min(0).max(60000).optional()}).strict(),gesture:z.enum(['point','pinch','pinch-hold','open-palm','swipe-left','swipe-right','none']),handedness:z.enum(['left','right']).optional(),diagnostics}).strict(),
 z.object({type:z.literal('presence'),state:z.enum(['present','absent','near']),confidence,observedAt:at}).strict(),
 z.object({type:z.literal('screen-context'),context}).strict(),z.object({type:z.enum(['camera.lost','camera.restored']),cameraId:text.optional(),observedAt:at}).strict(),z.object({type:z.literal('diagnostics'),diagnostics}).strict()
])}).strict();
