import { execFile } from 'node:child_process';import { access,readFile,stat,writeFile,unlink } from 'node:fs/promises';import { promisify } from 'node:util';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';
const run=promisify(execFile);const ps=(script:string)=>run('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout:5000});
export function validateLocalCapturePath(path:string){if(!/^[A-Za-z]:[\\/]/.test(path)||!path.toLowerCase().endsWith('.png')||path.includes('\0'))throw new Error('capture requires an absolute local PNG path');return path;}
async function assertLocalCaptureDisk(path:string){validateLocalCapturePath(path);const root=path.slice(0,2)+'\\';const {stdout}=await ps(`[IO.DriveInfo]::new('${root}').DriveType.ToString()`);if(!['Fixed','Removable','Ram'].includes(stdout.trim()))throw new Error('capture destination must be a local disk');}
export async function readCursor(){const{stdout}=await ps("Add-Type -AssemblyName System.Windows.Forms;$p=[System.Windows.Forms.Cursor]::Position;@{activeWindowTitle='unavailable';cursorX=$p.X;cursorY=$p.Y}|ConvertTo-Json -Compress");return JSON.parse(stdout)as{activeWindowTitle:string;cursorX:number;cursorY:number}}
export async function captureRegion(input:{x:number;y:number;width:number;height:number;outputPath:string;extractText?:boolean}){await assertLocalCaptureDisk(input.outputPath);const path=input.outputPath.replaceAll("'","''");await writeFile(input.outputPath,'',{flag:'wx'});try{await ps(`Add-Type -AssemblyName System.Drawing;$b=New-Object Drawing.Bitmap ${input.width},${input.height};$g=[Drawing.Graphics]::FromImage($b);try{$g.CopyFromScreen(${input.x},${input.y},0,0,$b.Size);$b.Save('${path}',[Drawing.Imaging.ImageFormat]::Png)}finally{$g.Dispose();$b.Dispose()}`);}catch{await unlink(input.outputPath).catch(()=>undefined);throw new Error('selected capture unavailable');}return readCapturedRegion(input)}
/** Independent verifier reads the existing selected artifact; never captures new pixels. */
export async function readCapturedRegion(input:{outputPath:string;extractText?:boolean}){
 await assertLocalCaptureDisk(input.outputPath);
 const metadata=await stat(input.outputPath);if(!metadata.isFile()||metadata.size>100000000)throw new Error('selected capture unavailable');
 const base={localPath:input.outputPath,capturedAt:metadata.mtime.toISOString()};if(!input.extractText)return base;
 const bytes=await readFile(input.outputPath);const {stdout}=await run('powershell.exe',['-NoProfile','-NonInteractive','-File',fileURLToPath(new URL('../scripts/selected-region-ocr.ps1',import.meta.url)),'-ImagePath',input.outputPath],{windowsHide:true,timeout:15000,maxBuffer:128000});
 const result=JSON.parse(stdout) as {text:string};if(typeof result.text!=='string'||result.text.length>16000)throw new Error('local OCR returned invalid derived text');return{...base,selectedText:result.text,imageSha256:createHash('sha256').update(bytes).digest('hex')};
}
export async function localFileExists(path:string){try{await access(path);return true}catch{return false}}
