import type { SemanticScene } from '@jarvis/scene';
const now = new Date().toISOString();
export const demoScene: SemanticScene = { id: 'primary-workspace', principalId: 'principal', version: 42, presentation: 'WORKING', updatedAt: now,
  monitors: [{ id: 'primary', label: 'Primary', bounds: { x: 0, y: 0, width: 1920, height: 1080 }, workArea: { x: 0, y: 0, width: 1920, height: 1040 }, scaleFactor: 1, primary: true, connected: true }], selectedProjectId: 'scalesmiths', objects: [
    { id: 'core', kind: 'jarvis-core', title: 'JARVIS', semanticRole: 'system-presence', monitorId: 'primary', position: { x: 760, y: 300 }, size: { width: 400, height: 400 }, zIndex: 1, state: 'focused', pinned: true, dismissible: false, resourceRefs: [], updatedAt: now, data: { activity: ['ATLAS', 'FORGE', 'WEB'], phrase: 'I have assembled the current operating picture.' } },
    { id: 'objectives', kind: 'objective', title: 'Objectives', semanticRole: 'desired-state', monitorId: 'primary', position: { x: 1180, y: 146 }, size: { width: 410, height: 270 }, zIndex: 2, state: 'expanded', pinned: false, dismissible: true, resourceRefs: ['objective:mk49'], updatedAt: now, data: { eyebrow: 'ACTIVE INTENT', primary: 'Shape the primary JARVIS experience', progress: 68, next: 'Validate spatial recovery across monitor change' } },
    { id: 'research', kind: 'research', title: 'Research', semanticRole: 'evidence-surface', monitorId: 'primary', position: { x: 165, y: 178 }, size: { width: 405, height: 315 }, zIndex: 2, state: 'expanded', pinned: false, dismissible: true, resourceRefs: ['research:spatial'], updatedAt: now, data: { eyebrow: 'SYNTHESIS', primary: 'Spatial interfaces should preserve causality, not decorate it.', sources: 12, confidence: 0.91 } },
    { id: 'infrastructure', kind: 'infrastructure', title: 'Infrastructure', semanticRole: 'system-topology', monitorId: 'primary', position: { x: 1230, y: 555 }, size: { width: 430, height: 285 }, zIndex: 2, state: 'expanded', pinned: false, dismissible: true, resourceRefs: ['node:workstation', 'node:server'], updatedAt: now, data: { eyebrow: 'SYSTEM FIELD', nodes: '—', healthy: '—', degraded: '—' } },
    { id: 'business', kind: 'revenue', title: 'ScaleSmiths', semanticRole: 'business-context', monitorId: 'primary', position: { x: 245, y: 600 }, size: { width: 420, height: 250 }, zIndex: 2, state: 'expanded', pinned: false, dismissible: true, resourceRefs: ['business:scalesmiths'], updatedAt: now, data: { eyebrow: 'BUSINESS', primary: 'Business context is ready to connect', signal: 'No authoritative business projection is available.' } },
  ] };
