'use client';
import { useEffect, useMemo, useRef } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Preload } from '@react-three/drei';
import { Bloom, EffectComposer } from '@react-three/postprocessing';
import { AdditiveBlending, BufferAttribute, BufferGeometry, Group } from 'three';
import type { AudioVisualEnvelope, JarvisOperatingPicture, SemanticScene } from '@jarvis/scene';
import type { ForgeVisualPolicy } from './forge-visual-policy.ts';
import { seededUnit } from './forge-visual-policy.ts';
import { ForgeRenderLoop } from './forge-render-loop.ts';
import { coreVisualPolicy } from './core-visual-policy.ts';

export interface ForgeRendererMetrics { fps:number; frameTimeMs:number; drawCalls:number; triangles:number; particleCount:number; quality:string; }

function positions(count:number,seed:number,spread:[number,number,number]){const values=new Float32Array(count*3);for(let i=0;i<count;i++){values[i*3]=(seededUnit(seed,i*3)-.5)*spread[0];values[i*3+1]=(seededUnit(seed,i*3+1)-.5)*spread[1];values[i*3+2]=(seededUnit(seed,i*3+2)-.5)*spread[2]}return values}
function PointsField({count,seed,color,size,spread,opacity}:{count:number;seed:number;color:string;size:number;spread:[number,number,number];opacity:number}){const geometry=useMemo(()=>{const g=new BufferGeometry();g.setAttribute('position',new BufferAttribute(positions(count,seed,spread),3));return g},[count,seed,spread[0],spread[1],spread[2]]);useEffect(()=>()=>geometry.dispose(),[geometry]);return <points geometry={geometry}><pointsMaterial color={color} size={size} transparent opacity={opacity} depthWrite={false} blending={AdditiveBlending}/></points>}

function NeuralConstellation({policy}:{policy:ForgeVisualPolicy}){const group=useRef<Group>(null);const geometry=useMemo(()=>{const nodes=positions(policy.neuralCount,42,[12,7,5]);const line=new Float32Array((policy.neuralCount-1)*6);for(let i=0;i<policy.neuralCount-1;i++){line.set(nodes.slice(i*3,i*3+3),i*6);line.set(nodes.slice((i+1)*3,(i+2)*3),i*6+3)}const g=new BufferGeometry();g.setAttribute('position',new BufferAttribute(line,3));return g},[policy.neuralCount]);useEffect(()=>()=>geometry.dispose(),[geometry]);useFrame((_,delta)=>{if(group.current)group.current.rotation.y+=delta*.018*policy.motion});return <group ref={group}><PointsField count={policy.neuralCount} seed={42} color="#55d9ff" size={.045} spread={[12,7,5]} opacity={.18+.65*policy.cyanEnergy}/><lineSegments geometry={geometry}><lineBasicMaterial color="#238eaa" transparent opacity={.05+.24*policy.cyanEnergy}/></lineSegments></group>}

function Nebula({policy}:{policy:ForgeVisualPolicy}){const group=useRef<Group>(null);useFrame(({clock})=>{if(group.current)group.current.rotation.z=Math.sin(clock.elapsedTime*.025)*.08*policy.motion});return <group ref={group} position={[-2,.4,-7]}><mesh scale={[7,3.4,1]}><sphereGeometry args={[1,24,16]}/><meshBasicMaterial color="#0b2730" transparent opacity={.07+.05*policy.cyanEnergy} depthWrite={false} blending={AdditiveBlending}/></mesh><mesh position={[4,-1,-1]} scale={[5,2.2,1]}><sphereGeometry args={[1,20,12]}/><meshBasicMaterial color="#39220c" transparent opacity={.035+.06*policy.goldEnergy} depthWrite={false} blending={AdditiveBlending}/></mesh></group>}

function EnergyPathways({policy}:{policy:ForgeVisualPolicy}){const group=useRef<Group>(null);const active=policy.state==='ROUTING'||policy.state==='EXECUTION';useFrame(({clock})=>{if(group.current)group.current.position.x=active?((clock.elapsedTime*.7)%4)-2:0});if(!active)return null;return <group ref={group}>{[-1.6,-.8,0,.8,1.6].map((y,index)=><mesh key={y} position={[-3,y,-.5-index*.05]}><sphereGeometry args={[.035+(index%2)*.015,6,6]}/><meshBasicMaterial color={policy.state==='EXECUTION'?'#ffb12b':'#51d7ee'}/></mesh>)}</group>}

function ForgeCore({policy,picture,envelope}:{policy:ForgeVisualPolicy;picture?:JarvisOperatingPicture;envelope:AudioVisualEnvelope}){const group=useRef<Group>(null);const scan=useRef<Group>(null);const visual=coreVisualPolicy(picture);const audio=visual.waveform*envelope.amplitude;useFrame(({clock},delta)=>{if(group.current){group.current.rotation.y+=delta*(.025+visual.orbitSpeed*.18)*policy.motion;const scale=1-visual.compression*.08+Math.sin(clock.elapsedTime*1.4)*.012*policy.motion+audio*.08;group.current.scale.setScalar(scale)}if(scan.current)scan.current.rotation.z=clock.elapsedTime*2.2*visual.scan});const color=visual.fracture?'#e43d2f':visual.incompleteOrbit?'#e19b32':visual.gold>.5?'#ffb62e':'#51d7ee';return <group ref={group}>
  <mesh><sphereGeometry args={[1.9,24,16]}/><meshBasicMaterial color="#183238" transparent opacity={.018+audio*.055} wireframe/></mesh>
  {[1.52,1.3,1.08].map((radius,index)=><mesh key={radius} rotation={[index*.7,.35+index*.4,index*.55]}><torusGeometry args={[radius,.012+index*.004,5,96]}/><meshBasicMaterial color={index===2&&visual.gold>.5?'#ffad25':'#4acbe8'} transparent opacity={(visual.incompleteOrbit&&index===0?.14:.2)+visual.cyan*.18}/></mesh>)}
  <mesh scale={1+audio*.16}><icosahedronGeometry args={[.82,3]}/><meshStandardMaterial color="#0b0d0e" metalness={.95} roughness={.18} emissive={color} emissiveIntensity={.32+visual.gold*.85+audio*.7} wireframe/></mesh>
  <mesh rotation={[Math.PI/2,0,0]} scale={1+audio*.2}><ringGeometry args={[1.72+audio*.08,1.735+audio*.12,64]}/><meshBasicMaterial color="#bdefff" transparent opacity={.08+visual.waveform*.25+audio*.55}/></mesh>
  <group ref={scan} rotation={[1.2,0,0]}><mesh><torusGeometry args={[1.86,.018,5,96,Math.PI*(visual.incompleteOrbit?1.45:2)]}/><meshBasicMaterial color={visual.incompleteOrbit?'#e19b32':'#7de8c4'} transparent opacity={.08+visual.scan*.68}/></mesh></group>
  {visual.routeEnergy?[[-2.3,0,0],[2.3,.3,0],[0,2.25,0]].map((position,index)=><mesh key={index} position={position as [number,number,number]}><cylinderGeometry args={[.018,.045,1.3,6]}/><meshBasicMaterial color="#55d9ff" transparent opacity={.65}/></mesh>):null}
  {visual.confirmation?<mesh><sphereGeometry args={[2.18,32,16]}/><meshBasicMaterial color="#72e2b2" transparent opacity={.12} wireframe/></mesh>:null}
  {visual.fracture?<mesh position={[.72,.4,.35]} rotation={[.4,.3,.8]}><tetrahedronGeometry args={[.32,1]}/><meshBasicMaterial color="#e43d2f" wireframe/></mesh>:null}
  <pointLight color={color} intensity={3+visual.gold*7+audio*3} distance={9}/>
 </group>}

function TechnicalGeometry({policy}:{policy:ForgeVisualPolicy}){const ref=useRef<Group>(null);useFrame((_,delta)=>{if(ref.current)ref.current.rotation.z-=delta*.006*policy.motion});return <group ref={ref} position={policy.state==='DEGRADED'?[.22,-.12,0]:[0,0,0]} rotation={[1.2,0,policy.state==='DEGRADED'?.08:0]}><mesh><torusGeometry args={[5.8,.008,4,96]}/><meshBasicMaterial color={policy.state==='DEGRADED'?'#a56b22':'#584626'} transparent opacity={.18}/></mesh><mesh rotation={[0,.3,.8]}><torusGeometry args={[7.4,.006,4,128]}/><meshBasicMaterial color="#314049" transparent opacity={.12}/></mesh>{policy.state==='CRITICAL'?<mesh position={[3.8,1.4,.2]} rotation={[.4,.2,.8]}><tetrahedronGeometry args={[.34,0]}/><meshBasicMaterial color="#d72f24" wireframe transparent opacity={.7}/></mesh>:null}</group>}

function SceneRepresentation({scene}:{scene:SemanticScene}){return <group>{scene.objects.filter(object=>object.kind!=='jarvis-core').slice(0,12).map((object,index)=><mesh key={object.id} position={[(object.position.x/1920-.5)*11,(.5-object.position.y/1080)*6,-1.5-index*.03]}><octahedronGeometry args={[.045,0]}/><meshBasicMaterial color="#d7aa55" transparent opacity={.28}/></mesh>)}</group>}

function RenderClock({fps,hidden}:{fps:number;hidden:boolean}){const advance=useThree(state=>state.advance);useEffect(()=>{if(hidden)return;const host={request:(callback:FrameRequestCallback)=>requestAnimationFrame(callback),cancel:(id:number)=>cancelAnimationFrame(id),now:()=>performance.now()};const loop=new ForgeRenderLoop(host,time=>advance(time,true),fps);loop.start();return()=>loop.stop()},[advance,fps,hidden]);return null}
function Metrics({policy,onMetrics}:{policy:ForgeVisualPolicy;onMetrics?:(metrics:ForgeRendererMetrics)=>void}){const gl=useThree(state=>state.gl);const sample=useRef({at:performance.now(),frames:0});useFrame(()=>{if(!onMetrics)return;sample.current.frames++;const now=performance.now();const elapsed=now-sample.current.at;if(elapsed>=500){onMetrics({fps:sample.current.frames*1000/elapsed,frameTimeMs:elapsed/sample.current.frames,drawCalls:gl.info.render.calls,triangles:gl.info.render.triangles,particleCount:policy.particleCount+policy.starCount+policy.neuralCount,quality:policy.quality});sample.current={at:now,frames:0}}});return null}

function Cosmos({scene,picture,envelope,policy,hidden,onMetrics}:{scene:SemanticScene;picture?:JarvisOperatingPicture;envelope:AudioVisualEnvelope;policy:ForgeVisualPolicy;hidden:boolean;onMetrics?:(metrics:ForgeRendererMetrics)=>void}){const core=scene.objects.find(object=>object.kind==='jarvis-core');const corePosition:[number,number,number]=core?[(core.position.x/1920-.5)*11,(.5-core.position.y/1080)*6,0]:[0,0,0];return <><RenderClock fps={policy.maxFps} hidden={hidden}/><color attach="background" args={['#020304']}/><fog attach="fog" args={['#020304',8,28]}/><ambientLight intensity={.12}/><Nebula policy={policy}/><PointsField count={policy.starCount} seed={7} color="#9bb8c2" size={.018} spread={[28,16,18]} opacity={.38}/><PointsField count={policy.particleCount} seed={91} color={policy.state==='CRITICAL'?'#dc4535':'#d18a31'} size={.025} spread={[18,10,12]} opacity={.16+.22*policy.goldEnergy}/><NeuralConstellation policy={policy}/><EnergyPathways policy={policy}/><TechnicalGeometry policy={policy}/><group position={corePosition}><ForgeCore policy={policy} picture={picture} envelope={envelope}/></group><SceneRepresentation scene={scene}/><Metrics policy={policy} onMetrics={onMetrics}/><Preload all/>{policy.bloom?<EffectComposer multisampling={0}><Bloom intensity={.42} luminanceThreshold={.68} mipmapBlur/></EffectComposer>:null}</>}

export default function ForgeCanvas({scene,picture,envelope,policy,hidden,onMetrics}:{scene:SemanticScene;picture?:JarvisOperatingPicture;envelope:AudioVisualEnvelope;policy:ForgeVisualPolicy;hidden:boolean;onMetrics?:(metrics:ForgeRendererMetrics)=>void}){return <Canvas className="forge-canvas" frameloop="never" dpr={policy.dpr} camera={{position:[0,0,9],fov:48}} gl={{antialias:policy.quality!=='LOW',alpha:false,powerPreference:policy.quality==='LOW'?'low-power':'high-performance'}}><Cosmos scene={scene} picture={picture} envelope={envelope} policy={policy} hidden={hidden} onMetrics={onMetrics}/></Canvas>}
