'use client';
import { useMemo, useState } from 'react';
import { AnimatePresence } from 'motion/react';
import { Activity, AudioLines, Command, Cpu, ShieldCheck, WifiOff } from 'lucide-react';
import type { DesktopApproval, DesktopApprovalCommand, DesktopKernelSnapshot, SceneIntent, SemanticScene } from '@jarvis/scene';
import { demoScene } from './demo-scene.ts';
import { JarvisCore } from './jarvis-core.tsx';
import { BrowserLayoutCache, createDesktopTransport, LocalSceneTransport } from './scene-client.ts';
import { SpatialPanel } from './spatial-panel.tsx';
import { useScene } from './use-scene.ts';
import { AirTouchLayer } from './air-touch-layer.tsx';

const offlineScene = (): SemanticScene => ({ id: 'kernel-offline', principalId: 'unavailable', version: 0, presentation: 'DEGRADED', monitors: [{ id: 'primary', label: 'Primary', bounds: { x: 0, y: 0, width: 1920, height: 1080 }, workArea: { x: 0, y: 0, width: 1920, height: 1040 }, scaleFactor: 1, primary: true, connected: true }], objects: [{ id: 'core', kind: 'jarvis-core', title: 'JARVIS', semanticRole: 'connection-status', monitorId: 'primary', position: { x: 760, y: 300 }, size: { width: 400, height: 400 }, zIndex: 1, state: 'focused', pinned: true, dismissible: false, resourceRefs: [], updatedAt: new Date().toISOString(), data: { activity: [], phrase: 'Kernel unavailable. No authoritative state is being shown.' } }], updatedAt: new Date().toISOString() });

export function JarvisExperience() {
  const demoMode = process.env.NEXT_PUBLIC_JARVIS_DEMO_MODE === '1';
  const transport = useMemo(() => demoMode ? new LocalSceneTransport(demoScene, new BrowserLayoutCache()) : createDesktopTransport(), [demoMode]);
  const { scene: receivedScene, kernel, connection, submit, submitCognition, decideApproval, reconnect } = useScene(transport);
  const scene = receivedScene ?? offlineScene(); const presentation = connection.status === 'offline' || connection.status === 'reconnecting' ? 'DEGRADED' : scene.presentation;
  const [selected, setSelected] = useState<string[]>([]); const [diagnostics, setDiagnostics] = useState(false); const [proposalOpen, setProposalOpen] = useState(false); const [proposalText, setProposalText] = useState(''); const [commandResult, setCommandResult] = useState('');
  const core = scene.objects.find((o) => o.kind === 'jarvis-core'); const panels = scene.objects.filter((o) => o.kind !== 'jarvis-core'); const send = (intent: SceneIntent) => void submit(intent).catch(() => setCommandResult('Presentation update conflicted; live state retained.'));
  const connectionLabel = connection.status === 'live' ? 'SYNCHRONISED' : connection.status === 'demo' ? 'DEMO MODE' : connection.status === 'connecting' ? 'CONNECTING' : connection.status === 'reconnecting' ? 'RECONNECTING' : 'KERNEL OFFLINE';
  const runProposal = async () => { try { if (!kernel) throw new Error('Kernel offline'); const result = await submitCognition({ commandId: crypto.randomUUID(), expectedStateVersion: kernel.stateVersion, input: proposalText }); setCommandResult(result.answer ?? `${result.result.proposals.length} proposal(s) returned by ${result.result.agentId}`); setProposalOpen(false); } catch (error) { setCommandResult(error instanceof Error ? error.message : String(error)); } };
  return <main className={`environment presentation-${presentation.toLowerCase()}`} onKeyDown={(e) => { if (e.key === 'Escape' && selected[0]) send({ type: 'dismiss', targetId: selected[0], input: 'keyboard' }); }} tabIndex={-1}>
    <div className="ambient-grid"/><div className="depth-field"/><header className="system-bar"><div className="identity"><span className="sigil">J</span><div><small>PRIMARY INTELLIGENCE</small><strong>JARVIS <em>MK.42</em></strong></div></div><div className="mode-selector" role="status" aria-label="Kernel presentation state"><span className="active">{presentation}</span><span>{kernel?.diagnostics.mode ?? 'UNAVAILABLE'}</span><span>{kernel?.principalId ?? 'NO PRINCIPAL'}</span></div><div className="system-time"><button className="connection-state" onClick={() => void reconnect()} title="Reconnect to Kernel">{connection.status === 'live' || connection.status === 'demo' ? <ShieldCheck size={14}/> : <WifiOff size={14}/>} {connectionLabel}</button><time>{new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit'}).format(new Date())}</time></div></header>
    <section className="workspace" aria-label="Semantic workspace"><div className="axis axis-x"/><div className="axis axis-y"/>{core&&<div className="core-position" style={{left:core.position.x,top:core.position.y}}><JarvisCore state={presentation} activity={core.data.activity as string[]}/><p>{String(core.data.phrase)}</p></div>}<AnimatePresence>{panels.map((object)=><SpatialPanel key={object.id} object={object} selected={selected.includes(object.id)} onSelect={(id)=>setSelected([id])} submit={send}/>)}</AnimatePresence></section>
    <footer className="command-deck"><button aria-label="RTC listening unavailable" disabled title="Listening is enabled only by live RTC state"><AudioLines size={17}/></button><button className="command-line" onClick={()=>setProposalOpen(!proposalOpen)} disabled={connection.status!=='live'}><Command size={15}/><span>{connection.status==='live'?'Ask JARVIS or request an action':'Commands unavailable until Kernel reconnects'}</span><kbd>ENTER</kbd></button><button aria-label="Open diagnostics" className={diagnostics?'active':''} onClick={()=>setDiagnostics(!diagnostics)}><Activity size={17}/></button></footer>
    {proposalOpen&&<section className="proposal-entry"><label htmlFor="proposal-json">JARVIS REQUEST</label><textarea id="proposal-json" value={proposalText} onChange={(event)=>setProposalText(event.target.value)} placeholder="Ask a question or describe the outcome you want."/><div><button onClick={()=>setProposalOpen(false)}>CANCEL</button><button onClick={()=>void runProposal()}>SUBMIT TO JARVIS</button></div></section>}
    {commandResult&&<div className="command-result" role="status">{commandResult}</div>}
    <AirTouchLayer objects={panels} submit={send}/><div className="gesture-indicator"><span/><small>AIR TOUCH · {connection.status==='live'?'PRESENTATION READY':'LOCAL ONLY'}</small></div>
    {diagnostics&&<Diagnostics snapshot={kernel} status={connectionLabel} onClose={()=>setDiagnostics(false)}/>} {kernel?.approvals.map((approval)=><ApprovalCard key={approval.id} approval={approval} stateVersion={kernel.stateVersion} decide={decideApproval}/>) }
  </main>;
}

function ApprovalCard({ approval, stateVersion, decide }: { approval: DesktopApproval; stateVersion: number; decide: (command: DesktopApprovalCommand)=>Promise<void> }) {
  const [busy,setBusy]=useState(false); const [result,setResult]=useState(''); const [confirmation,setConfirmation]=useState(''); const act=async(decision:'approve'|'deny')=>{setBusy(true);try{await decide({commandId:crypto.randomUUID(),expectedStateVersion:stateVersion,approvalId:approval.id,invocationId:approval.invocationId,nonce:approval.nonce!,version:approval.version!,decision,...(confirmation?{confirmationPhrase:confirmation}:{})});setResult(decision==='approve'?'Approved and resumed through Kernel':'Denied by operator');}catch(error){setResult(error instanceof Error?error.message:String(error));}finally{setBusy(false);}};
  return <aside className="approval" aria-label="Approval required"><header><div><ShieldCheck size={15}/><span>APPROVAL REQUIRED</span></div></header><h2>{approval.action}</h2><dl><dt>Capability</dt><dd>{approval.capabilityId}</dd><dt>Actor</dt><dd>{approval.actor}</dd><dt>Affected resource</dt><dd>{approval.resource}</dd><dt>Reason</dt><dd>{approval.reason}</dd><dt>Risk</dt><dd>{approval.riskClass}</dd><dt>Scope</dt><dd>{approval.scopes.join(', ')||'No declared scopes'}</dd><dt>Expires</dt><dd>{approval.expiresAt}</dd><dt>Arguments</dt><dd><pre>{JSON.stringify(approval.arguments,null,2)}</pre></dd></dl>{approval.riskClass==='CRITICAL'&&<input className="confirmation" value={confirmation} onChange={(event)=>setConfirmation(event.target.value)} placeholder="Required confirmation phrase"/>}{result?<p>{result}</p>:<div className="approval-actions"><button disabled={busy} onClick={()=>void act('deny')}>DENY</button><button disabled={busy} onClick={()=>void act('approve')}>APPROVE</button></div>}</aside>;
}

function Diagnostics({ snapshot, status, onClose }: { snapshot?: DesktopKernelSnapshot; status:string; onClose:()=>void }) {
  const dependency=(name:string)=>snapshot?.diagnostics.dependencies.find((item)=>item.name===name)?.status??'UNAVAILABLE'; const rows=[['CONNECTION',status],['EVENT RATE',snapshot?`${snapshot.diagnostics.events.ratePerMinute}/MIN`:'UNAVAILABLE'],['EVENT FABRIC',dependency('event-bus')],['NATS',dependency('nats')],['POSTGRES',dependency('postgres')],['REDIS',dependency('redis')],['MODEL GATEWAY',dependency('model-gateway')],['SESSIONS',snapshot?String(snapshot.sessions.length):'UNAVAILABLE'],['CAPABILITY ACTIVITY',snapshot?String(snapshot.capabilityActivity.length):'UNAVAILABLE'],['POLICY DENIALS',snapshot?String(snapshot.policyDenials.length):'UNAVAILABLE'],['STATE VERSION',snapshot?String(snapshot.stateVersion):'UNAVAILABLE']];
  return <aside className="diagnostics" aria-label="Developer diagnostics"><header><div><Cpu size={15}/><span>LIVE KERNEL FIELD</span></div><button onClick={onClose}>CLOSE</button></header><h2>System coherence</h2><p>{snapshot?`Snapshot ${snapshot.generatedAt}`:'No Kernel snapshot. Values are unavailable, not inferred.'}</p><div className="diag-grid">{rows.map(([name,value])=><div key={name}><small>{name}</small><strong>{value}</strong><i className={value==='HEALTHY'||value==='live'?'':'observe'}/></div>)}</div></aside>;
}
