'use client';
import { useEffect, useMemo, useState } from 'react'; import { AnimatePresence } from 'motion/react'; import { Activity, AudioLines, Command, Cpu, ShieldCheck, WifiOff } from 'lucide-react'; import type { PresentationState, SceneIntent } from '@jarvis/scene'; import { demoScene } from './demo-scene.ts'; import { JarvisCore } from './jarvis-core.tsx'; import { BrowserLayoutCache, LocalSceneTransport } from './scene-client.ts'; import { SpatialPanel } from './spatial-panel.tsx'; import { useScene } from './use-scene.ts';
import { AirTouchLayer } from './air-touch-layer.tsx';
const states: PresentationState[] = ['DORMANT', 'LISTENING', 'THINKING', 'WORKING', 'ALERT', 'GUARDIAN', 'DEGRADED'];
export function JarvisExperience() { const transport = useMemo(() => new LocalSceneTransport(demoScene, new BrowserLayoutCache()), []); const { scene, connected, submit } = useScene(transport); const [selected, setSelected] = useState<string[]>([]); const [presentation, setPresentation] = useState<PresentationState>('WORKING'); const [diagnostics, setDiagnostics] = useState(false); useEffect(() => transport.restoreCached(), [transport]); if (!scene) return null;
  const core = scene.objects.find((o) => o.kind === 'jarvis-core'); const panels = scene.objects.filter((o) => o.kind !== 'jarvis-core'); const send = (intent: SceneIntent) => void submit(intent);
  return <main className={`environment presentation-${presentation.toLowerCase()}`} onKeyDown={(e) => { if (e.key === 'Escape' && selected[0]) send({ type: 'dismiss', targetId: selected[0], input: 'keyboard' }); }} tabIndex={-1}>
    <div className="ambient-grid" /><div className="depth-field" /><header className="system-bar"><div className="identity"><span className="sigil">J</span><div><small>PRIMARY INTELLIGENCE</small><strong>JARVIS <em>MK.42</em></strong></div></div><div className="mode-selector" role="group" aria-label="Presentation state">{states.map((state) => <button key={state} className={presentation === state ? 'active' : ''} onClick={() => setPresentation(state)}>{state}</button>)}</div><div className="system-time"><span>{connected ? <ShieldCheck size={14} /> : <WifiOff size={14} />}{connected ? 'SYNCHRONISED' : 'RECONNECTING'}</span><time>{new Intl.DateTimeFormat('en-GB', { hour: '2-digit', minute: '2-digit' }).format(new Date())}</time></div></header>
    <section className="workspace" aria-label="Semantic workspace"><div className="axis axis-x" /><div className="axis axis-y" />{core && <div className="core-position" style={{ left: core.position.x, top: core.position.y }}><JarvisCore state={presentation} activity={core.data.activity as string[]} /><p>{String(core.data.phrase)}</p></div>}<AnimatePresence>{panels.map((object) => <SpatialPanel key={object.id} object={object} selected={selected.includes(object.id)} onSelect={(id) => setSelected([id])} submit={send} />)}</AnimatePresence></section>
    <footer className="command-deck"><button aria-label="Begin listening" onClick={() => setPresentation('LISTENING')}><AudioLines size={17} /></button><div className="command-line"><Command size={15} /><span>Ask JARVIS, or reference anything in space</span><kbd>⌘ K</kbd></div><button aria-label="Open diagnostics" className={diagnostics ? 'active' : ''} onClick={() => setDiagnostics(!diagnostics)}><Activity size={17} /></button></footer>
    <AirTouchLayer objects={panels} submit={send} /><div className="gesture-indicator"><span /><small>AIR TOUCH · READY</small></div>{diagnostics && <Diagnostics onClose={() => setDiagnostics(false)} />}
  </main>;
}
function Diagnostics({ onClose }: { onClose: () => void }) { const rows = [['EVENT FABRIC','184 / min','nominal'],['CORE LATENCY','18 ms','nominal'],['HAND LATENCY','31 ms','nominal'],['NATS QUEUE','0','nominal'],['POSTGRES','connected','nominal'],['REDIS','connected','nominal'],['MODEL COST','£0.18 / h','nominal'],['POLICY DENIALS','3','observe']]; return <aside className="diagnostics" aria-label="Developer diagnostics"><header><div><Cpu size={15} /><span>INTERNAL FIELD</span></div><button onClick={onClose}>CLOSE</button></header><h2>System coherence</h2><p>Diagnostics are sampled independently of render cadence.</p><div className="diag-grid">{rows.map(([name, value, state]) => <div key={name}><small>{name}</small><strong>{value}</strong><i className={state} /></div>)}</div></aside>; }
