import { describe, expect, it, vi } from 'vitest';
import type { DesktopKernelSnapshot, SemanticScene } from '@jarvis/scene';
import { KernelSceneTransport, type LayoutCache } from './scene-client.ts';

const scene = (version = 7): SemanticScene => ({ id: 'live', principalId: 'p', version, presentation: 'WORKING', monitors: [], objects: [], updatedAt: '2026-09-04T00:00:00Z' });
const snapshot = (version = 7) => ({ schemaVersion: 1, generatedAt: '2026-09-04T00:00:00Z', stateVersion: version, principalId: 'p', scene: scene(version), approvals: [], sessions: [], notifications: [], objectives: [], capabilityActivity: [], policyDenials: [], selectedProjectId: null, contextId: null, diagnostics: { mode: 'AUTONOMOUS' }, state: {} } as unknown as DesktopKernelSnapshot);
const response = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
const cache: LayoutCache = { read: () => undefined, write: () => undefined };

describe('live Kernel scene transport', () => {
  it('receives a genuine Kernel snapshot and authenticates the connection', async () => { const fetch = vi.fn<typeof globalThis.fetch>(async (_input, _init) => response(snapshot())); const transport = new KernelSceneTransport({ endpoint: 'http://core', token: 'token', cache, fetch, pollMs: 60_000 }); let live: DesktopKernelSnapshot | undefined; let status = ''; transport.subscribeKernel((value) => { live = value; }); transport.subscribeConnection((value) => { status = value.status; }); await vi.waitFor(() => expect(status).toBe('live')); expect(live?.stateVersion).toBe(7); expect(fetch.mock.calls[0]?.[1]?.headers).toMatchObject({ authorization: 'Bearer token' }); transport.close(); });
  it('stays alive offline and reconnect restores authoritative state', async () => { let attempts = 0; const fetch = vi.fn<typeof globalThis.fetch>(async (_input, _init) => { attempts++; if (attempts === 1) throw new Error('network partition'); return response(snapshot(9)); }); const transport = new KernelSceneTransport({ endpoint: 'http://core', token: 'token', cache, fetch, pollMs: 60_000 }); let status = ''; let version = 0; transport.subscribeConnection((value) => { status = value.status; }); transport.subscribeKernel((value) => { version = value?.stateVersion ?? version; }); await vi.waitFor(() => expect(status).toBe('offline')); await transport.reconnect(); await vi.waitFor(() => expect(status).toBe('live')); expect(version).toBe(9); transport.close(); });
  it('rejects stale command state and refreshes instead of replaying it', async () => { const fetch = vi.fn<typeof globalThis.fetch>(async (_input, init) => init?.method === 'POST' ? response({ error: 'state_version_conflict', currentStateVersion: 8 }, 409) : response(snapshot(8))); const transport = new KernelSceneTransport({ endpoint: 'http://core', token: 'token', cache, fetch, pollMs: 60_000 }); let status = ''; transport.subscribeConnection((value) => { status = value.status; }); await vi.waitFor(() => expect(status).toBe('live')); await expect(transport.submitProposal({ commandId: 'c', expectedStateVersion: 7, proposal: {} as never })).rejects.toThrow('STATE_VERSION_CONFLICT'); expect(fetch.mock.calls.filter((call) => call[1]?.method === 'POST')).toHaveLength(1); transport.close(); });
  it('submits approval binding fields exactly and never calls an adapter', async () => { const fetch = vi.fn<typeof globalThis.fetch>(async (_input, init) => init?.method === 'POST' ? response({ accepted: true }) : response(snapshot())); const transport = new KernelSceneTransport({ endpoint: 'http://core', token: 'token', cache, fetch, pollMs: 60_000 }); let status = ''; transport.subscribeConnection((value) => { status = value.status; }); await vi.waitFor(() => expect(status).toBe('live')); await transport.decideApproval({ commandId: 'cmd', expectedStateVersion: 7, approvalId: 'approval', invocationId: 'invocation', nonce: 'nonce', version: 3, decision: 'deny' }); const body = JSON.parse(String(fetch.mock.calls.find((call) => call[1]?.method === 'POST')?.[1]?.body)); expect(body).toEqual({ commandId: 'cmd', expectedStateVersion: 7, approvalId: 'approval', invocationId: 'invocation', nonce: 'nonce', version: 3, decision: 'deny' }); expect(fetch.mock.calls.some((call) => String(call[0]).includes('adapter'))).toBe(false); transport.close(); });
  it('rejects commands while disconnected rather than queueing unsafe work', async () => { const transport = new KernelSceneTransport({ endpoint: 'http://core', token: 'token', cache, fetch: vi.fn(async () => { throw new Error('offline'); }), pollMs: 60_000 }); let status = ''; transport.subscribeConnection((value) => { status = value.status; }); await vi.waitFor(() => expect(status).toBe('offline')); await expect(transport.submitProposal({ commandId: 'c', expectedStateVersion: 0, proposal: {} as never })).rejects.toThrow('KERNEL_OFFLINE_COMMAND_REJECTED'); transport.close(); });
});
