import { describe, expect, it, vi } from 'vitest';
import type { DesktopKernelSnapshot, ExperienceServerMessage, SemanticScene } from '@jarvis/scene';
import { KernelSceneTransport, type LayoutCache } from './scene-client.ts';
const scene=(version=7):SemanticScene=>({id:'live',principalId:'p',version,presentation:'WORKING',monitors:[],objects:[],updatedAt:'2026-09-29T00:00:00Z'});
const snapshot=(version=7)=>({schemaVersion:2,operatingPictureVersion:1,generatedAt:'2026-09-29T00:00:00Z',stateVersion:version,sceneVersion:version,systemMode:'AMBIENT',interactionState:'INTERPRETING',workState:'EXECUTING',principal:{id:'p',status:'active'},presence:{status:'present'},activeTasks:[],activeModels:[],recentModelRuns:[],activeAgents:[],activeCapabilities:[],systemHealth:{},telemetrySummary:{availability:'unavailable',generatedAt:'2026-09-29T00:00:00Z',traceExport:'inactive'},pendingApprovals:[],conversationActivity:{activeSessionIds:[],activeRunIds:[],recentResponseIds:[]},selectedContext:{contextId:null,projectId:null},principalId:'p',scene:scene(version),approvals:[],sessions:[],notifications:[],objectives:[],cognitionResponses:[],capabilityActivity:[],policyDenials:[],selectedProjectId:null,contextId:null,diagnostics:{mode:'AUTONOMOUS'},state:{}} as unknown as DesktopKernelSnapshot);
const response=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});const cache:LayoutCache={read:()=>undefined,write:()=>undefined};
class FakeSocket {readyState=1;onopen:null|(()=>void)=null;onmessage:null|((event:{data:string})=>void)=null;onclose:null|((event:{code:number;reason:string})=>void)=null;onerror:null|(()=>void)=null;sent:string[]=[];send(data:string){this.sent.push(data)}close(code=1000,reason=''){this.readyState=3;this.onclose?.({code,reason})}open(){this.onopen?.()}message(value:ExperienceServerMessage){this.onmessage?.({data:JSON.stringify(value)})}}
function harness(initial=7){const sockets:FakeSocket[]=[];const fetch=vi.fn<typeof globalThis.fetch>(async(input)=>String(input).includes('/auth/session')?response({accessToken:'a'.repeat(43),credential:{sessionId:'session'}},201):response(snapshot(initial)));const transport=new KernelSceneTransport({endpoint:'http://core',credential:'secret',nodeId:'local-server',cache,fetch,socket:()=>{const socket=new FakeSocket();sockets.push(socket);return socket},retryBaseMs:1,retryMaxMs:2});return{transport,fetch,sockets}}
describe('realtime Kernel scene transport',()=>{
  it('explains model unavailability without reflecting provider details or pretending the Kernel disconnected',async()=>{
    const{transport,fetch,sockets}=harness();let status='';transport.subscribeConnection(value=>{status=value.status});
    await vi.waitFor(()=>expect(sockets).toHaveLength(1));sockets[0]!.open();sockets[0]!.message({type:'experience.ready',schemaVersion:1,streamId:'s',sequence:1,heartbeatMs:10_000});
    fetch.mockResolvedValueOnce(response({error:'untrusted-provider-detail-canary'},503));
    const command=transport.submitCognition({commandId:'offline',expectedStateVersion:7,input:'Reason about this'});
    await expect(command).rejects.toThrow('Model inference unavailable. Local state');expect(status).toBe('live');transport.close();
  });
  it('bootstraps once, authenticates the WebSocket subscription, and stops polling',async()=>{const{transport,fetch,sockets}=harness();let status='';transport.subscribeConnection((value)=>{status=value.status});transport.subscribeKernel(()=>undefined);await vi.waitFor(()=>expect(sockets).toHaveLength(1));sockets[0]!.open();const sent=JSON.parse(sockets[0]!.sent[0]!) as{accessToken:string;sessionId:string;channels:string[]};expect(sent).toMatchObject({accessToken:'a'.repeat(43),sessionId:'session'});expect(sent.channels).toContain('scene');sockets[0]!.message({type:'experience.ready',schemaVersion:1,streamId:'s',sequence:1,heartbeatMs:10_000});expect(status).toBe('live');expect(fetch.mock.calls.filter(([url])=>String(url).includes('/desktop/snapshot'))).toHaveLength(1);transport.close()});
  it('applies a typed push update without another snapshot request',async()=>{const{transport,fetch,sockets}=harness();let version=0;transport.subscribeKernel((value)=>{version=value?.stateVersion??version});await vi.waitFor(()=>expect(sockets).toHaveLength(1));sockets[0]!.open();sockets[0]!.message({type:'experience.update',schemaVersion:1,streamId:'s',sequence:1,generatedAt:'2026-09-29T00:00:01Z',stateVersion:8,sceneVersion:8,channels:['system','scene'],full:true,patch:snapshot(8)});expect(version).toBe(8);expect(fetch.mock.calls.filter(([url])=>String(url).includes('/desktop/snapshot'))).toHaveLength(1);transport.close()});
  it('marks retained authoritative data stale when disconnected',async()=>{const{transport,sockets}=harness();let state='';transport.subscribeConnection((value)=>{state=value.status});await vi.waitFor(()=>expect(sockets).toHaveLength(1));sockets[0]!.open();sockets[0]!.message({type:'experience.ready',schemaVersion:1,streamId:'s',sequence:1,heartbeatMs:10_000});sockets[0]!.close(1006,'network lost');expect(state).toBe('reconnecting');await expect(transport.submitProposal({commandId:'c',expectedStateVersion:7,proposal:{} as never})).rejects.toThrow('KERNEL_OFFLINE_COMMAND_REJECTED');transport.close()});
  it('rejects agent cancellation while disconnected rather than inventing a cancelled state',async()=>{
    const{transport,sockets,fetch}=harness();transport.subscribeConnection(()=>undefined);await vi.waitFor(()=>expect(sockets).toHaveLength(1));sockets[0]!.open();sockets[0]!.message({type:'experience.ready',schemaVersion:1,streamId:'s',sequence:1,heartbeatMs:10_000});sockets[0]!.close(1006,'lost');
    await expect(transport.cancelAgentJob({commandId:'cancel',jobId:'job',expectedStateVersion:7})).rejects.toThrow('KERNEL_OFFLINE_COMMAND_REJECTED');
    expect(fetch.mock.calls.some(([url])=>String(url).endsWith('/desktop/agents/cancel'))).toBe(false);transport.close();
  });
  it('reconnects with bounded retry and presents its resume position',async()=>{const{transport,sockets}=harness();transport.subscribeConnection(()=>undefined);await vi.waitFor(()=>expect(sockets).toHaveLength(1));sockets[0]!.open();sockets[0]!.message({type:'experience.update',schemaVersion:1,streamId:'s',sequence:4,generatedAt:'2026-09-29T00:00:01Z',stateVersion:8,sceneVersion:8,channels:['system','scene'],full:true,patch:snapshot(8)});sockets[0]!.close(1006,'lost');await vi.waitFor(()=>expect(sockets.length).toBeGreaterThan(1));sockets[1]!.open();expect(JSON.parse(sockets[1]!.sent[0]!).resume).toEqual({streamId:'s',sequence:4});transport.close()});
  it('rejects stale commands and recovers through the snapshot endpoint',async()=>{const{transport,fetch,sockets}=harness();fetch.mockImplementation(async(input,init)=>String(input).includes('/auth/session')?response({accessToken:'a'.repeat(43),credential:{sessionId:'session'}},201):init?.method==='POST'?response({error:'state_version_conflict'},409):response(snapshot(9)));let status='';transport.subscribeConnection((value)=>{status=value.status});await vi.waitFor(()=>expect(sockets).toHaveLength(1));sockets[0]!.open();sockets[0]!.message({type:'experience.ready',schemaVersion:1,streamId:'s',sequence:1,heartbeatMs:10_000});expect(status).toBe('live');await expect(transport.submitProposal({commandId:'c',expectedStateVersion:7,proposal:{} as never})).rejects.toThrow('STATE_VERSION_CONFLICT');transport.close()});
});
