'use client';
import {useState} from 'react';
import type {DesktopKernelSnapshot,DesktopProposalCommand} from '@jarvis/scene';
export function SelectedCapture({kernel,live,submit}:{kernel?:DesktopKernelSnapshot;live:boolean;submit:(command:DesktopProposalCommand)=>Promise<unknown>}){
 const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [region,setRegion]=useState({x:'0',y:'0',width:'640',height:'240',outputPath:''});
 async function propose(){if(!kernel?.principalId||!live)return;const input={x:Number(region.x),y:Number(region.y),width:Number(region.width),height:Number(region.height),outputPath:region.outputPath,extractText:true};if(![input.x,input.y,input.width,input.height].every(Number.isSafeInteger)||input.width<=0||input.height<=0||!input.outputPath.trim()){setMessage('Enter an explicit region and local PNG output path.');return;}setBusy(true);try{const correlationId=crypto.randomUUID();await submit({commandId:crypto.randomUUID(),expectedStateVersion:kernel.stateVersion,proposal:{proposalId:crypto.randomUUID(),kind:'capability_invocation',correlationId,confidence:1,provenance:{method:'assertion',producedBy:kernel.principalId,producedOn:'desktop',producedAt:new Date().toISOString(),correlationId,derivedFromUntrusted:false},invocation:{capabilityId:'capabilities.windows',capabilityVersion:'1.2.0',action:'capture_region',input},justification:'Operator explicitly selected this screen region for local error-text analysis.'}});setMessage('Capture proposed. Review the separate approval card before pixels are read.');}catch{setMessage('Capture proposal unavailable. Check the enabled workstation capability and operator grant.');}finally{setBusy(false);}}
 return <div className="selected-capture"><button disabled={!live} onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Select screen region for capture">CAPTURE</button>{open&&<section aria-label="Selected screen capture"><p>Enter physical screen coordinates. Only this region will be saved locally after approval. OCR text stays local.</p>{(['x','y','width','height','outputPath'] as const).map(key=><label key={key}>{key==='outputPath'?'Local PNG path':key.toUpperCase()}<input type={key==='outputPath'?'text':'number'} value={region[key]} onChange={event=>setRegion({...region,[key]:event.target.value})}/></label>)}<button disabled={busy||!live} onClick={()=>void propose()}>PROPOSE CAPTURE</button><button onClick={()=>setOpen(false)}>CLOSE</button><p role="status">{message}</p></section>}</div>;
}

