'use client';
import { useEffect, useRef, useState } from 'react'; import { AnimatePresence, motion, useReducedMotion } from 'motion/react'; import { ChevronsUp, Focus, Grip, Pin, X } from 'lucide-react'; import type { SceneIntent, SceneObject } from '@jarvis/scene';
export function SpatialPanel({ object, selected, onSelect, submit, live=true }: { object: SceneObject; selected: boolean; onSelect: (id: string) => void; submit: (intent: SceneIntent) => void;live?:boolean }) { const reduce = useReducedMotion(); const dragStart = useRef(object.position); const [local, setLocal] = useState(object.position); const data = object.data;
  const dragCleanup=useRef<()=>void>(()=>{});
  useEffect(()=>setLocal(object.position),[object.position.x,object.position.y]);
  useEffect(()=>()=>dragCleanup.current(),[]);
  return <motion.article data-scene-id={object.id} layout={!reduce} className={`spatial-panel kind-${object.kind} ${selected ? 'selected' : ''} state-${object.state}`} style={{ left: `${local.x/1920*100}%`, top: `${local.y/1080*100}%`, width: `${object.size.width/1920*100}%`, minHeight: object.state === 'collapsed' ? 54 : `${object.size.height/1080*100}vh`, zIndex: object.zIndex }} initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .96 }} transition={{ duration: reduce ? 0 : .22 }} onPointerDown={() => onSelect(object.id)}>
    <header onPointerDown={(event) => { if (event.button !== 0 || (event.target as HTMLElement).closest('button')) return; dragCleanup.current(); const origin = { x: event.clientX, y: event.clientY }; const workspace=event.currentTarget.parentElement?.parentElement; const scaleX=(workspace?.clientWidth??1920)/1920,scaleY=(workspace?.clientHeight??1080)/1080; const position=(e:PointerEvent)=>({x:dragStart.current.x+(e.clientX-origin.x)/Math.max(.01,scaleX),y:dragStart.current.y+(e.clientY-origin.y)/Math.max(.01,scaleY)}); dragStart.current = local; event.currentTarget.setPointerCapture(event.pointerId); const move = (e: PointerEvent) => setLocal(position(e)); const clean=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);window.removeEventListener('pointercancel',cancel);}; const up = (e: PointerEvent) => { clean(); submit({ type: 'move', targetId: object.id, monitorId: object.monitorId, position:position(e), input: 'mouse' }); }; const cancel=()=>{clean();setLocal(object.position);};dragCleanup.current=clean; window.addEventListener('pointermove', move); window.addEventListener('pointerup', up);window.addEventListener('pointercancel',cancel); }}>
      <div className="panel-title"><Grip size={13} /><span>{live?String(data.eyebrow ?? object.semanticRole):'LAST OBSERVED'}</span><strong>{object.title}</strong></div><div className="panel-actions"><button aria-label={`Focus ${object.title}`} onClick={() => submit({ type: 'focus', targetId: object.id, input: 'mouse' })}><Focus size={14} /></button><button aria-label={`${object.pinned ? 'Unpin' : 'Pin'} ${object.title}`} onClick={() => submit({ type: 'pin', targetId: object.id, input: 'mouse' })}><Pin size={14} /></button><button aria-label={`${object.state === 'collapsed' ? 'Expand' : 'Collapse'} ${object.title}`} onClick={() => submit({ type: object.state === 'collapsed' ? 'expand' : 'collapse', targetId: object.id, input: 'mouse' })}><ChevronsUp size={14} /></button>{object.dismissible && <button aria-label={`Dismiss ${object.title}`} onClick={() => submit({ type: 'dismiss', targetId: object.id, input: 'mouse' })}><X size={14} /></button>}</div>
    </header><AnimatePresence>{object.state !== 'collapsed' && <motion.div className="panel-content" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>{!live&&<p role="status">Disconnected: recorded references are stale.</p>}{renderPanel(object,live)}</motion.div>}</AnimatePresence>
  </motion.article>;
}
function renderPanel(object: SceneObject,live:boolean) {
  const data = object.data;
  const metric = (value: unknown) => live&&typeof value === 'number' && Number.isFinite(value) ? String(value) : 'Unavailable';
  if (object.kind === 'objective') return <><p className="lead">{String(data.primary ?? 'Objective unavailable')}</p>{live&&typeof data.progress === 'number' && Number.isFinite(data.progress) ? <div className="progress" role="progressbar" aria-label="Observed objective progress" aria-valuenow={data.progress}><i style={{ width: `${Math.max(0, Math.min(100, data.progress))}%` }} /></div> : <p className="signal">Progress not measured</p>}<dl><dt>Next verified state</dt><dd>{String(data.next ?? 'Unavailable')}</dd></dl></>;
  if (object.kind === 'infrastructure') return <><p className="signal">Observed Kernel dependencies and admitted connections</p><div className="metrics"><span><b>{metric(data.healthy)}</b> healthy dependencies</span><span><b>{metric(data.degraded)}</b> non-healthy dependencies</span><span><b>{metric(data.nodes)}</b> connected nodes</span></div><p className="signal">{object.resourceRefs.join(' · ') || 'No connected node references'}</p></>;
  if (object.kind === 'research') return <><blockquote>{String(data.primary ?? 'Research unavailable')}</blockquote><div className="evidence"><span>{metric(data.sources)} sources</span><span>{live&&typeof data.confidence === 'number' && Number.isFinite(data.confidence) ? `${Math.round(data.confidence * 100)}% reported confidence` : 'Confidence unavailable'}</span></div></>;
  return <><p className="lead">{String(data.primary ?? 'Unavailable')}</p><p className="signal">{String(data.signal ?? '')}</p></>;
}
