'use client';
import { useRef, useState } from 'react'; import { AnimatePresence, motion, useReducedMotion } from 'motion/react'; import { ChevronsUp, Focus, Grip, Pin, X } from 'lucide-react'; import type { SceneIntent, SceneObject } from '@jarvis/scene';
export function SpatialPanel({ object, selected, onSelect, submit }: { object: SceneObject; selected: boolean; onSelect: (id: string) => void; submit: (intent: SceneIntent) => void }) { const reduce = useReducedMotion(); const dragStart = useRef(object.position); const [local, setLocal] = useState(object.position); const data = object.data;
  return <motion.article data-scene-id={object.id} layout={!reduce} className={`spatial-panel kind-${object.kind} ${selected ? 'selected' : ''} state-${object.state}`} style={{ left: local.x, top: local.y, width: object.size.width, minHeight: object.state === 'collapsed' ? 54 : object.size.height, zIndex: object.zIndex }} initial={{ opacity: 0, scale: .97 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: .96 }} transition={{ duration: reduce ? 0 : .22 }} onPointerDown={() => onSelect(object.id)}>
    <header onPointerDown={(event) => { if (event.button !== 0) return; const origin = { x: event.clientX, y: event.clientY }; dragStart.current = local; event.currentTarget.setPointerCapture(event.pointerId); const move = (e: PointerEvent) => setLocal({ x: dragStart.current.x + e.clientX - origin.x, y: dragStart.current.y + e.clientY - origin.y }); const up = (e: PointerEvent) => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', up); submit({ type: 'move', targetId: object.id, monitorId: object.monitorId, position: { x: dragStart.current.x + e.clientX - origin.x, y: dragStart.current.y + e.clientY - origin.y }, input: 'mouse' }); }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', up); }}>
      <div className="panel-title"><Grip size={13} /><span>{String(data.eyebrow ?? object.semanticRole)}</span><strong>{object.title}</strong></div><div className="panel-actions"><button aria-label={`Focus ${object.title}`} onClick={() => submit({ type: 'focus', targetId: object.id, input: 'mouse' })}><Focus size={14} /></button><button aria-label={`${object.pinned ? 'Unpin' : 'Pin'} ${object.title}`} onClick={() => submit({ type: 'pin', targetId: object.id, input: 'mouse' })}><Pin size={14} /></button><button aria-label={`${object.state === 'collapsed' ? 'Expand' : 'Collapse'} ${object.title}`} onClick={() => submit({ type: object.state === 'collapsed' ? 'expand' : 'collapse', targetId: object.id, input: 'mouse' })}><ChevronsUp size={14} /></button>{object.dismissible && <button aria-label={`Dismiss ${object.title}`} onClick={() => submit({ type: 'dismiss', targetId: object.id, input: 'mouse' })}><X size={14} /></button>}</div>
    </header><AnimatePresence>{object.state !== 'collapsed' && <motion.div className="panel-content" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>{renderPanel(object)}</motion.div>}</AnimatePresence>
  </motion.article>;
}
function renderPanel(object: SceneObject) { const data = object.data; if (object.kind === 'objective') return <><p className="lead">{String(data.primary)}</p><div className="progress"><i style={{ width: `${Number(data.progress)}%` }} /></div><dl><dt>Next verified state</dt><dd>{String(data.next)}</dd></dl></>; if (object.kind === 'infrastructure') return <><div className="topology"><span>WORKSTATION</span><i /><b>CORE</b><i /><span>LOCAL SERVER</span></div><div className="metrics"><span><b>{String(data.healthy)}</b> nominal</span><span><b>{String(data.degraded)}</b> degraded</span><span><b>{String(data.nodes)}</b> nodes</span></div></>; if (object.kind === 'research') return <><blockquote>{String(data.primary)}</blockquote><div className="evidence"><span>{String(data.sources)} sources</span><span>{Math.round(Number(data.confidence) * 100)}% confidence</span></div></>; return <><p className="lead">{String(data.primary)}</p><p className="signal">{String(data.signal ?? '')}</p><div className="trace"><i /><i /><i /><i /></div></>; }
