import { EventNames,type VoiceEventCommand,type VoiceEventResponse } from '@jarvis/contracts';import type{SessionManager}from'../session/session-manager.ts';import type{ModeManager}from'../mode/mode-manager.ts';import type{CognitionOrchestrator}from'../cognition/cognition-orchestrator.ts';import type{EventManager}from'../event-fabric/event-manager.ts';
export class VoiceGateway{constructor(private d:{sessions:SessionManager;mode:ModeManager;cognition:CognitionOrchestrator;events:EventManager;token:string;principalId:string}){}authenticate(value:string|undefined){return Boolean(this.d.token)&&value===`Bearer ${this.d.token}`}authorises(principalId:string){return principalId===this.d.principalId}
 async handle(command:VoiceEventCommand):Promise<VoiceEventResponse>{let session=command.event.sessionId?await this.d.sessions.get(command.event.sessionId):null;if(command.event.type==='activation'){if(!session){session=await this.d.sessions.open({type:'rtc',principalId:command.principalId,nodeId:command.nodeId,correlationId:command.commandId,contextRef:'voice-conversation'});const activated=await this.d.sessions.transition({sessionId:session.id,to:'active',reason:command.event.activation,expectedVersion:session.version});if(activated.ok)session=activated.session}await this.mode('ENGAGED','interaction_started','voice activated');await this.emit(EventNames.VoiceActivated,command,session.id,{activation:command.event.activation,deviceId:command.event.deviceId});return{sessionId:session.id,state:'listening'}}
  if(!session||session.principalId!==command.principalId||!session.nodes.includes(command.nodeId))throw new Error('voice session not found or not owned by principal/node');await this.d.sessions.touch(session.id);
  if(command.event.type==='asr.partial'){await this.emit(EventNames.VoicePartial,command,session.id,{text:command.event.text,sequence:command.event.sequence});return{sessionId:session.id,state:'listening'}}
  if(command.event.type==='asr.final'){await this.emit(EventNames.VoiceTranscript,command,session.id,{text:command.event.text,sequence:command.event.sequence});await this.mode('FOCUSED','focus_requested','voice cognition');const cognition=await this.d.cognition.submit({requestId:command.commandId,principalId:command.principalId,correlationId:command.commandId,input:command.event.text,agentId:'agents.oracle',task:'reason',realtime:true,maxLatencyMs:15000});await this.mode('ENGAGED','focus_released','voice response ready');return{sessionId:session.id,state:'speaking',cognition,...(cognition.answer?{utterance:cognition.answer}:{})}}
  if(command.event.type==='barge-in'){await this.emit(EventNames.VoiceBargeIn,command,session.id,{});await this.mode('ENGAGED','focus_released','barge in');return{sessionId:session.id,state:'listening'}}
  if(command.event.type==='silence'){await this.emit(EventNames.VoiceSilence,command,session.id,{durationMs:command.event.durationMs});return{sessionId:session.id,state:'idle'}}
  if(command.event.type==='device.changed'){await this.emit(EventNames.VoiceDeviceChanged,command,session.id,{deviceId:command.event.deviceId});return{sessionId:session.id,state:'listening'}}
  if(command.event.type==='device.lost'){await this.emit(EventNames.VoiceDeviceLost,command,session.id,{deviceId:command.event.deviceId});return{sessionId:session.id,state:'degraded'}}
  const ended=await this.d.sessions.transition({sessionId:session.id,to:'ended',reason:'voice deactivated',expectedVersion:-1});await this.mode('AMBIENT','interaction_ended','voice deactivated');return{sessionId:session.id,state:ended.ok?'idle':'degraded'} }
 private async mode(to:'AMBIENT'|'ENGAGED'|'FOCUSED',trigger:'interaction_started'|'interaction_ended'|'focus_requested'|'focus_released',reason:string){if(await this.d.mode.current()!==to)await this.d.mode.requestTransition(to,trigger,reason)}
 private async emit(type:string,c:VoiceEventCommand,sessionId:string,payload:unknown){await this.d.events.emit({type:type as never,retentionClass:type===EventNames.VoicePartial?'TRANSIENT':'OPERATIONAL',privacyClass:'SENSITIVE',subject:{kind:'session',id:sessionId},actor:{kind:'principal',id:c.principalId},correlationId:c.commandId,causationId:c.commandId,principalId:c.principalId,payload}).catch(()=>undefined)} }
