import type { InvocationLifecycle, InvocationState } from '@jarvis/contracts';
import { TERMINAL_INVOCATION_STATES } from '@jarvis/contracts';
import { advance } from './lifecycle.ts';
import type { Sql } from '@jarvis/persistence';
export interface InvocationStorePort {
  create(row: InvocationLifecycle): Promise<void>;
  get(id: string): Promise<InvocationLifecycle | undefined>;
  byProposal(id: string): Promise<InvocationLifecycle | undefined>;
  transition(id: string, state: InvocationState, at: string, eventId: string): Promise<void>;
  patch(id: string, values: Partial<Pick<InvocationLifecycle, 'riskClass' | 'grantId' | 'grantVersion' | 'approvalRequestId' | 'resourceKey' | 'beforeStateRef' | 'verifyReportRef'>>): Promise<void>;
  orphaned(): Promise<InvocationLifecycle[]>;
}
export class InvocationStore {
  private readonly rows = new Map<string, InvocationLifecycle>();
  private readonly proposals = new Map<string, string>();
  async create(row: InvocationLifecycle) { if (this.rows.has(row.invocationId)) throw new Error('duplicate invocation'); if (row.proposalId && this.proposals.has(row.proposalId)) throw new Error('duplicate proposal'); this.rows.set(row.invocationId, structuredClone(row)); if (row.proposalId) this.proposals.set(row.proposalId, row.invocationId); }
  async get(id: string) { return this.rows.get(id); }
  async byProposal(id: string) { const invocationId = this.proposals.get(id); return invocationId ? this.rows.get(invocationId) : undefined; }
  async transition(id: string, state: InvocationState, at: string, eventId: string) { const row = this.rows.get(id); if (!row) throw new Error('invocation not found'); advance(row.state, state); row.state = state; row.history.push({ state, at, eventId }); if ((TERMINAL_INVOCATION_STATES as readonly string[]).includes(state)) row.finishedAt = at; }
  async patch(id: string, values: Partial<InvocationLifecycle>) { const row = this.rows.get(id); if (!row) throw new Error('invocation not found'); Object.assign(row, values); }
  async orphaned() { return [...this.rows.values()].filter((r) => ['EXECUTING', 'SIMULATING', 'ROLLING_BACK', 'COMPENSATING'].includes(r.state)); }
}

interface InvocationRow { invocation_id: string; proposal_id: string | null; capability_id: string; capability_version: string; action: string; state: InvocationState; correlation_id: string; principal_id: string; origin_actor: InvocationLifecycle['originActor']; risk_class: InvocationLifecycle['riskClass']; grant_id: string | null; grant_version: number | null; approval_request_id: string | null; resource_key: string | null; lease_id: string | null; input_hash: string; before_state_ref: string | null; predicted_effect_ref: string | null; verify_report_ref: string | null; started_at: string | null; finished_at: string | null; }
export class PgInvocationStore implements InvocationStorePort {
  constructor(private readonly sql: Sql) {}
  async create(row: InvocationLifecycle) { await this.sql`insert into agency.invocations (invocation_id, proposal_id, capability_id, capability_version, action, state, correlation_id, principal_id, origin_actor, risk_class, input_hash) values (${row.invocationId}, ${row.proposalId ?? null}, ${row.capabilityId}, ${row.capabilityVersion}, ${row.action}, ${row.state}, ${row.correlationId}, ${row.principalId}, ${JSON.stringify(row.originActor)}, ${row.riskClass}, ${row.inputHash})`; }
  async get(id: string) { const rows = await this.sql<InvocationRow[]>`select * from agency.invocations where invocation_id=${id} limit 1`; return rows[0] ? await this.map(rows[0]) : undefined; }
  async byProposal(id: string) { const rows = await this.sql<InvocationRow[]>`select * from agency.invocations where proposal_id=${id} limit 1`; return rows[0] ? await this.map(rows[0]) : undefined; }
  async transition(id: string, state: InvocationState, at: string, eventId: string) { const current = await this.get(id); if (!current) throw new Error('invocation not found'); advance(current.state, state); await this.sql.begin(async (tx) => { await tx`update agency.invocations set state=${state}, started_at=case when ${state}='EXECUTING' then ${at}::timestamptz else started_at end, finished_at=case when ${(TERMINAL_INVOCATION_STATES as readonly string[]).includes(state)} then ${at}::timestamptz else finished_at end where invocation_id=${id}`; await tx`insert into agency.invocation_history (invocation_id, state, at, event_id) values (${id}, ${state}, ${at}, ${eventId}) on conflict (event_id) do nothing`; }); }
  async patch(id: string, values: Partial<Pick<InvocationLifecycle, 'riskClass' | 'grantId' | 'grantVersion' | 'approvalRequestId' | 'resourceKey' | 'beforeStateRef' | 'verifyReportRef'>>) { await this.sql`update agency.invocations set risk_class=coalesce(${values.riskClass ?? null}, risk_class), grant_id=coalesce(${values.grantId ?? null}, grant_id), grant_version=coalesce(${values.grantVersion ?? null}, grant_version), approval_request_id=coalesce(${values.approvalRequestId ?? null}, approval_request_id), resource_key=coalesce(${values.resourceKey ?? null}, resource_key), before_state_ref=coalesce(${values.beforeStateRef ?? null}, before_state_ref), verify_report_ref=coalesce(${values.verifyReportRef ?? null}, verify_report_ref) where invocation_id=${id}`; }
  async orphaned() { const rows = await this.sql<InvocationRow[]>`select * from agency.invocations where state in ('EXECUTING','SIMULATING','ROLLING_BACK','COMPENSATING')`; return Promise.all(rows.map((row) => this.map(row))); }
  private async map(row: InvocationRow): Promise<InvocationLifecycle> { const history = await this.sql<{ state: InvocationState; at: string; event_id: string }[]>`select state, at, event_id from agency.invocation_history where invocation_id=${row.invocation_id} order by ordinal`; return { invocationId: row.invocation_id, ...(row.proposal_id ? { proposalId: row.proposal_id } : {}), capabilityId: row.capability_id, capabilityVersion: row.capability_version, action: row.action, state: row.state, correlationId: row.correlation_id, principalId: row.principal_id, originActor: row.origin_actor, riskClass: row.risk_class, inputHash: row.input_hash, history: history.map((item) => ({ state: item.state, at: new Date(item.at).toISOString(), eventId: item.event_id })), ...(row.grant_id ? { grantId: row.grant_id } : {}), ...(row.grant_version !== null ? { grantVersion: row.grant_version } : {}), ...(row.approval_request_id ? { approvalRequestId: row.approval_request_id } : {}), ...(row.resource_key ? { resourceKey: row.resource_key } : {}), ...(row.lease_id ? { leaseId: row.lease_id } : {}), ...(row.before_state_ref ? { beforeStateRef: row.before_state_ref } : {}), ...(row.predicted_effect_ref ? { predictedEffectRef: row.predicted_effect_ref } : {}), ...(row.verify_report_ref ? { verifyReportRef: row.verify_report_ref } : {}), ...(row.started_at ? { startedAt: new Date(row.started_at).toISOString() } : {}), ...(row.finished_at ? { finishedAt: new Date(row.finished_at).toISOString() } : {}) }; }
}
