import { startTelemetry, stopTelemetry, structuredLog } from '@jarvis/telemetry';
import { createInterface } from 'node:readline';
import { HttpVoiceKernel } from './kernel-client.ts'; import { VoiceEngine } from './voice-engine.ts'; import { WindowsSpeechInput, WindowsSpeechOutput } from './windows-speech.ts';
import { WakePhraseActivation } from './activation.ts';
import { LocalVoiceSidecar } from './local-sidecar.ts';
import { VoiceQualification } from './qualification.ts';
const kernel=new HttpVoiceKernel({url:process.env.JARVIS_CORE_URL??'http://127.0.0.1:7420',bootstrapCredential:process.env.JARVIS_BOOTSTRAP_CREDENTIAL??'dev-bootstrap-secret',principalId:process.env.JARVIS_VOICE_PRINCIPAL??'principal-operator',nodeId:process.env.JARVIS_NODE_ID??'local-server'});
const node=process.env.JARVIS_NODE_ID??'local-server';
startTelemetry({serviceName:'jarvis-voice',serviceVersion:'0.43.0',nodeId:node,otlpEndpoint:process.env.JARVIS_OTLP_ENDPOINT,disabled:process.env.JARVIS_TELEMETRY_DISABLED==='true'});
const log=(event:string)=>{void structuredLog({component:'voice',node,event});};
const wakePhrase=process.env.JARVIS_WAKE_PHRASE??'jarvis';
const requested=process.env.JARVIS_VOICE_ADAPTER??'windows';if(!['windows','local'].includes(requested))throw new Error('Voice adapter must be windows or local; cloud audio is not enabled');
const qualification=process.argv.includes('--qualify')?new VoiceQualification(requested):undefined;
let engine:VoiceEngine;
const env:Record<string,string>={};for(const k of ['JARVIS_ASR_MODEL_PATH','JARVIS_TTS_VOICE','PICOVOICE_ACCESS_KEY','HF_HOME'])if(process.env[k])env[k]=process.env[k]!;
const local=new LocalVoiceSidecar({python:process.env.JARVIS_VOICE_PYTHON,env,onPlayback:a=>engine?.playbackAmplitude(a)});
const makeEngine=(kind:string)=>new VoiceEngine({input:kind==='local'?local:new WindowsSpeechInput(),output:kind==='local'?local.output:new WindowsSpeechOutput(()=>engine.playbackStarted()),kernel,wakePhrase,activation:new WakePhraseActivation(wakePhrase),onState:s=>log('state.'+s),...(kind==='local'?{onEngaged:(value:boolean)=>local.engaged(value)}:{}),onMeasurement:qualification?.record});
engine=makeEngine(requested);
try{await engine.start();}catch(error){if(requested!=='local'||qualification)throw error;await local.stop();log('local.unavailable.fallback.windows');engine=makeEngine('windows');await engine.start();}log('runtime.ready');
if(qualification)console.log('Qualification: say Jarvis, ask a question, interrupt, then follow up. /mark <wake|partial|reply|barge-in|same-context|self-trigger|device-recovery|input-switch|output-switch> PASS|FAIL. /baseline start|stop /false-wake /self-trigger /report. No raw audio is saved.');
let publishing=false;const timer=setInterval(()=>{if(publishing)return;publishing=true;void kernel.send({type:'runtime.health',...engine.diagnostics()}).catch(()=>log('telemetry.unavailable')).finally(()=>{publishing=false;});},10000);timer.unref();
const cli=createInterface({input:process.stdin,output:process.stdout});
cli.on('line',(line)=>{void(async()=>{const[value,arg,result]=line.trim().split(/\s+/);if(value==='/listen'||value==='/ptt')await engine.activate(value==='/ptt'?'push-to-talk':'manual');else if(value==='/stop')await engine.deactivate();else if(value==='/device')await engine.switchDevice(arg??'default');else if(value==='/output')await engine.switchOutputDevice(arg??'default');else if(value==='/devices'){if(requested==='local')console.log(await local.enumerate());else console.log('System.Speech uses Windows default input/output. Select defaults in Windows Settings.');}else if(value==='/mark')qualification?.mark(arg??'',result??'');else if(value==='/baseline'&&(arg==='start'||arg==='stop')){if(arg==='start')await engine.deactivate();qualification?.baseline(arg);}else if(value==='/false-wake')qualification?.falseWake();else if(value==='/self-trigger')qualification?.selfTrigger();else if(value==='/report')console.log(qualification?.save()??'Run with --qualify');else if(value==='/quit'){qualification?.save();clearInterval(timer);await engine.stop();await stopTelemetry();process.exit(0)}})().catch(()=>log('command.failed'))});
for(const signal of ['SIGINT','SIGTERM'] as const)process.once(signal,()=>{qualification?.save();clearInterval(timer);void engine.stop().then(()=>stopTelemetry()).finally(()=>process.exit(0))});
