import type{VoiceActivationKind,VoicePerceptionEvent}from'@jarvis/contracts';import type{ActivationStrategy,RecognitionEvent,SpeechInput,SpeechOutput,VoiceKernel}from'./contracts.ts';import{BoundedRing}from'./ring-buffer.ts';
export type VoiceState='idle'|'listening'|'thinking'|'speaking'|'degraded';
export class VoiceEngine{state:VoiceState='idle';private active=false;private sequence=0;private speaking?:AbortController;private queue=new BoundedRing<RecognitionEvent>(64);constructor(private d:{input:SpeechInput;output:SpeechOutput;kernel:VoiceKernel;activation?:ActivationStrategy;wakePhrase?:string;onState?:(s:VoiceState)=>void}){}
 async start(){await this.d.input.start(e=>void this.receive(e))}async stop(){this.active=false;await this.interrupt();await this.d.input.stop();this.set('idle')}
 async activate(kind:VoiceActivationKind='manual',deviceId='default'){const response=await this.d.kernel.send({type:'activation',activation:kind,deviceId});this.active=true;this.set(response.state==='degraded'?'degraded':'listening')}
 async deactivate(){if(this.active)await this.d.kernel.send({type:'deactivate',sessionId:''});this.active=false;await this.interrupt();this.set('idle')}
 async switchDevice(deviceId:string){await this.d.input.switchDevice(deviceId);await this.d.kernel.send({type:'device.changed',deviceId})}
 private async receive(e:RecognitionEvent){this.queue.push(e);if(e.type==='device-lost'){this.set('degraded');if(this.active)await this.send({type:'device.lost',deviceId:e.deviceId,sessionId:''});return}if(e.type==='speech-start'&&this.state==='speaking'){await this.interrupt();await this.send({type:'barge-in',sessionId:''});this.set('listening');return}if(!this.active){const matched=this.d.activation?.matches(e)??(e.type==='final'&&e.text?.trim().toLowerCase().startsWith(this.d.wakePhrase??'jarvis'));if(matched){await this.activate(this.d.activation?.kind??'wake-phrase',e.deviceId);const rest=e.text?.trim().slice((this.d.wakePhrase??'jarvis').length).trim();if(rest)await this.final(rest)}return}if(e.type==='partial'&&e.text)await this.send({type:'asr.partial',text:e.text,sequence:++this.sequence,sessionId:''});else if(e.type==='final'&&e.text)await this.final(e.text);else if(e.type==='silence')await this.send({type:'silence',durationMs:e.durationMs??0,sessionId:''})}
 private async final(text:string){this.set('thinking');try{const response=await this.send({type:'asr.final',text,sequence:++this.sequence,sessionId:''});if(response.utterance){this.set('speaking');const controller=new AbortController();this.speaking=controller;await this.d.output.speak(response.utterance,controller.signal);if(this.speaking===controller){this.speaking=undefined;this.set('listening')}}else this.set(response.state)}catch{this.set('degraded')}}
 private send(event:VoicePerceptionEvent){return this.d.kernel.send(event)}private async interrupt(){if(this.speaking){this.speaking.abort();this.speaking=undefined}await this.d.output.stop()}private set(s:VoiceState){this.state=s;this.d.onState?.(s)}get bufferedFrames(){return this.queue.size}}
