import{describe,expect,it,vi}from'vitest';import type{RecognitionEvent,SpeechInput,SpeechOutput,VoiceKernel}from'./contracts.ts';import{VoiceEngine}from'./voice-engine.ts';
class Input implements SpeechInput{listener?:(e:RecognitionEvent)=>void;async start(l:(e:RecognitionEvent)=>void){this.listener=l}async stop(){}async switchDevice(){}emit(e:RecognitionEvent){this.listener?.(e)}}
const tick=()=>new Promise(r=>setTimeout(r,5));
describe('realtime voice state machine',()=>{it('activates, emits partial/final transcripts, and retains the Kernel session',async()=>{const input=new Input(),events:unknown[]=[];const kernel:VoiceKernel={async send(event){events.push(event);return event.type==='activation'?{sessionId:'rtc-1',state:'listening'}:{sessionId:'rtc-1',state:event.type==='asr.final'?'speaking':'listening',...(event.type==='asr.final'?{utterance:'It is noon.'}:{})}}};const output:SpeechOutput={speak:vi.fn(async()=>{}),stop:vi.fn(async()=>{})};const engine=new VoiceEngine({input,output,kernel});await engine.start();await engine.activate('push-to-talk');input.emit({type:'partial',text:'what time',deviceId:'mic'});input.emit({type:'final',text:'what time is it',deviceId:'mic'});await tick();expect(events).toEqual(expect.arrayContaining([expect.objectContaining({type:'asr.partial'}),expect.objectContaining({type:'asr.final'})]));expect(output.speak).toHaveBeenCalledWith('It is noon.',expect.any(AbortSignal));expect(engine.state).toBe('listening')});
it('stops speech when a genuine user hypothesis confirms barge-in',async()=>{const input=new Input(),events:string[]=[];let release!:()=>void;const output:SpeechOutput={speak:vi.fn((_t,signal)=>new Promise<void>(resolve=>{release=resolve;signal.addEventListener('abort',resolve)})),stop:vi.fn(async()=>{})};const kernel:VoiceKernel={async send(event){events.push(event.type);return{sessionId:'same-session',state:event.type==='asr.final'?'speaking':'listening',...(event.type==='asr.final'?{utterance:'I found seventeen results that match. '}: {})}}};const engine=new VoiceEngine({input,output,kernel});await engine.start();await engine.activate();input.emit({type:'final',text:'find results',deviceId:'mic'});await tick();expect(engine.state).toBe('speaking');input.emit({type:'speech-start',deviceId:'mic'});input.emit({type:'partial',text:'stop now please',deviceId:'mic'});await tick();expect(output.stop).toHaveBeenCalled();expect(events).toContain('barge-in');expect(engine.state).toBe('listening');release()});
it('suppresses recognizer echo of current TTS without disabling genuine interruption',async()=>{const input=new Input(),events:string[]=[];let release!:()=>void;const output:SpeechOutput={speak:vi.fn((_t,signal)=>new Promise<void>(resolve=>{release=resolve;signal.addEventListener('abort',resolve)})),stop:vi.fn(async()=>{})};const kernel:VoiceKernel={async send(event){events.push(event.type);return{sessionId:'s',state:event.type==='asr.final'?'speaking':'listening',...(event.type==='asr.final'?{utterance:'The weather is clear today'}:{})}}};const engine=new VoiceEngine({input,output,kernel});await engine.start();await engine.activate();input.emit({type:'final',text:'weather',deviceId:'mic'});await tick();input.emit({type:'speech-start',deviceId:'mic'});input.emit({type:'final',text:'the weather is clear today',deviceId:'mic'});await tick();expect(events).not.toContain('barge-in');expect(output.stop).not.toHaveBeenCalled();expect(engine.echoDiagnostics.suppressedCount).toBe(1);input.emit({type:'speech-start',deviceId:'mic'});input.emit({type:'partial',text:'actually stop now',deviceId:'mic'});await tick();expect(events).toContain('barge-in');release()});
it('keeps only bounded transient recognition data and degrades on device loss',async()=>{const input=new Input(),kernel:VoiceKernel={async send(){return{sessionId:'s',state:'degraded'}}},output:SpeechOutput={async speak(){},async stop(){}};const engine=new VoiceEngine({input,output,kernel});await engine.start();for(let i=0;i<100;i++)input.emit({type:'partial',text:String(i),deviceId:'mic'});expect(engine.bufferedFrames).toBe(64);input.emit({type:'device-lost',deviceId:'mic'});await tick();expect(engine.state).toBe('degraded')})});

it('reports failed observation delivery without exposing transcript content',async()=>{const input=new Input();const kernel:VoiceKernel={async send(event){if(event.type==='activation'||event.type==='audio.state')return{sessionId:'s',state:'listening'};throw new Error('private transcript');}};const engine=new VoiceEngine({input,output:{async speak(){},async stop(){}},kernel});await engine.start();await engine.activate();input.emit({type:'partial',text:'private transcript',deviceId:'mic'});await tick();expect(engine.diagnostics()).toMatchObject({ready:false,deviceReady:true,droppedObservations:1});expect(JSON.stringify(engine.diagnostics())).not.toContain('transcript');await engine.stop();});
