import{spawn,type ChildProcessWithoutNullStreams}from'node:child_process';import{createInterface}from'node:readline';import{fileURLToPath}from'node:url';import type{RecognitionEvent,SpeechInput,SpeechOutput}from'./contracts.ts';
export class WindowsSpeechInput implements SpeechInput{
 private child?:ChildProcessWithoutNullStreams;private listener?:(e:RecognitionEvent)=>void;private stopping=false;private retry?:ReturnType<typeof setTimeout>;
 async start(listener:(e:RecognitionEvent)=>void){if(process.platform!=='win32')throw new Error('Windows speech input requires Windows');this.stopping=false;this.listener=listener;this.spawn()}
 private spawn(){if(this.stopping||!this.listener)return;const script=fileURLToPath(new URL('../scripts/windows-speech.ps1',import.meta.url));const listener=this.listener;this.child=spawn('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',script],{stdio:'pipe',windowsHide:true});createInterface({input:this.child.stdout}).on('line',line=>{try{listener(JSON.parse(line)as RecognitionEvent)}catch{}});this.child.once('exit',()=>{if(this.stopping)return;listener({type:'device-lost',deviceId:'windows-default'});this.retry=setTimeout(()=>this.spawn(),1000)})}
 async stop(){this.stopping=true;if(this.retry)clearTimeout(this.retry);this.child?.kill();this.child=undefined}
 async switchDevice(deviceId:string){if(deviceId!=='default'&&deviceId!=='windows-default')throw new Error('Windows System.Speech supports the current default input only');const listener=this.listener;await this.stop();if(listener)await this.start(listener)}
}
export class WindowsSpeechOutput implements SpeechOutput{private child?:ChildProcessWithoutNullStreams;async speak(text:string,signal:AbortSignal){await this.stop();const escaped=text.replaceAll("'","''");const command=`Add-Type -AssemblyName System.Speech; $v=New-Object System.Speech.Synthesis.SpeechSynthesizer; $v.SelectVoiceByHints([System.Speech.Synthesis.VoiceGender]::Male,[System.Speech.Synthesis.VoiceAge]::Adult,0,[cultureinfo]'en-GB'); $v.Rate=-1; $v.Speak('${escaped}')`;const encoded=Buffer.from(command,'utf16le').toString('base64');this.child=spawn('powershell.exe',['-NoProfile','-NonInteractive','-EncodedCommand',encoded],{stdio:'pipe',windowsHide:true});signal.addEventListener('abort',()=>void this.stop(),{once:true});await new Promise<void>((resolve,reject)=>{this.child!.once('exit',code=>code===0||signal.aborted?resolve():reject(new Error(`TTS exited ${code}`)));this.child!.once('error',reject)})}async stop(){if(this.child&&!this.child.killed)this.child.kill();this.child=undefined}}
