import { EventNames, type Objective, type ObjectiveOrigin, type ObjectiveStatus, type Provenance, type SuccessCriterion } from '@jarvis/contracts';
import type { Sql } from '@jarvis/persistence'; import type { Clock } from '../../runtime/clock.ts'; import type { IdGen } from '../../runtime/ids.ts'; import type { EventManager } from '../event-fabric/event-manager.ts';
const legal:Record<ObjectiveStatus,ObjectiveStatus[]>={proposed:['active','abandoned'],active:['blocked','paused','achieved','failed','abandoned'],blocked:['active','paused','failed','abandoned'],paused:['active','abandoned'],achieved:[],abandoned:[],failed:[]};
interface Row{objective_id:string;principal_id:string;parent_objective_id:string|null;statement:string;origin:ObjectiveOrigin;status:ObjectiveStatus;success_criteria:SuccessCriterion[];child_objective_ids:string[];dependencies:string[];next_actions:string[];desired_state:Record<string,unknown>;next_evaluation_at:string|null;constraints:string[];authority:Objective['authority'];priority:number;deadline:string|null;provenance:Provenance;correlation_id:string;created_at:string;updated_at:string}
const j=(v:unknown)=>JSON.stringify(v);
export class ObjectiveEngine{
 constructor(private readonly d:{sql:Sql;events:EventManager;clock:Clock;ids:IdGen}){}
 async exclusive<T>(id:string,principalId:string,run:()=>Promise<T>):Promise<T>{return this.d.sql.begin(async tx=>{const [lock]=await tx<{locked:boolean}[]>`select pg_try_advisory_xact_lock(hashtextextended(${`nova:${id}`},0)) as locked`;if(!lock?.locked)throw new Error('objective workflow already running');const objective=await this.get(id);if(!objective||objective.principalId!==principalId)throw new Error('objective principal mismatch');return run()}) as Promise<T>}
 async create(input:{principalId:string;statement:string;origin:ObjectiveOrigin;correlationId:string;successCriteria?:SuccessCriterion[];dependencies?:string[];nextActions?:string[];desiredState?:Record<string,unknown>;nextEvaluationAt?:string;constraints?:string[];priority?:number;deadline?:string;provenance:Provenance;parentObjectiveId?:string}){const id=this.d.ids.ulid(),now=this.d.clock.nowIso();await this.d.sql`insert into projections.objectives(objective_id,principal_id,parent_objective_id,statement,origin,status,success_criteria,child_objective_ids,dependencies,next_actions,desired_state,next_evaluation_at,constraints,authority,priority,deadline,provenance,correlation_id,created_at,updated_at) values(${id},${input.principalId},${input.parentObjectiveId??null},${input.statement},${input.origin},'proposed',${j(input.successCriteria??[])},${j([])},${j(input.dependencies??[])},${j(input.nextActions??[])},${j(input.desiredState??{})},${input.nextEvaluationAt??null},${j(input.constraints??[])},${j({mayReason:true,mayPlan:true,mayPropose:true,mayExecute:false})},${input.priority??50},${input.deadline??null},${j(input.provenance)},${input.correlationId},${now},${now})`;await this.record(id,'proposed','created',now);await this.emit(EventNames.ObjectiveCreated,id,input.principalId,input.correlationId,{statement:input.statement});return(await this.get(id))!}
 async get(id:string):Promise<Objective|undefined>{const[r]=await this.d.sql<Row[]>`select * from projections.objectives where objective_id=${id}`;if(!r)return;const history=await this.d.sql<Objective['history']>`select status,at,reason from projections.objective_history where objective_id=${id} order by sequence`;return this.map(r,history)}
 async list(principalId:string){const rows=await this.d.sql<Row[]>`select * from projections.objectives where principal_id=${principalId} order by priority desc,created_at`;return Promise.all(rows.map(async r=>this.map(r,await this.d.sql<Objective['history']>`select status,at,reason from projections.objective_history where objective_id=${r.objective_id} order by sequence`)))}
 async update(id:string,p:{statement?:string;priority?:number;deadline?:string|null;dependencies?:string[];nextActions?:string[];desiredState?:Record<string,unknown>;nextEvaluationAt?:string|null;constraints?:string[]}){const c=await this.get(id);if(!c)throw new Error('objective not found');await this.d.sql`update projections.objectives set statement=${p.statement??c.statement},priority=${p.priority??c.priority},deadline=${p.deadline===undefined?(c.deadline??null):p.deadline},dependencies=${j(p.dependencies??c.dependencies)},next_actions=${j(p.nextActions??c.nextActions)},desired_state=${j(p.desiredState??c.desiredState)},next_evaluation_at=${p.nextEvaluationAt===undefined?(c.nextEvaluationAt??null):p.nextEvaluationAt},constraints=${j(p.constraints??c.constraints)},updated_at=${this.d.clock.nowIso()},version=version+1 where objective_id=${id}`;return(await this.get(id))!}
 pause(id:string,r:string){return this.transition(id,'paused',r)}resume(id:string,r:string){return this.transition(id,'active',r)}cancel(id:string,r:string){return this.transition(id,'abandoned',r)}complete(id:string,r:string){return this.transition(id,'achieved',r)}fail(id:string,r:string){return this.transition(id,'failed',r)}
 async transition(id:string,to:ObjectiveStatus,reason:string){const c=await this.get(id);if(!c)throw new Error('objective not found');if(!legal[c.status].includes(to))throw new Error(`illegal objective transition ${c.status} -> ${to}`);const now=this.d.clock.nowIso();await this.d.sql.begin(async tx=>{const[l]=await tx<{status:ObjectiveStatus}[]>`select status from projections.objectives where objective_id=${id} for update`;if(!l||l.status!==c.status)throw new Error('objective changed concurrently');await tx`update projections.objectives set status=${to},updated_at=${now},version=version+1 where objective_id=${id}`;await tx`insert into projections.objective_history(objective_id,status,reason,at) values(${id},${to},${reason},${now})`});await this.emit(EventNames.ObjectiveTransitioned,id,c.principalId,c.correlationId,{from:c.status,to,reason});return(await this.get(id))!}
 private record(id:string,s:ObjectiveStatus,r:string,at:string){return this.d.sql`insert into projections.objective_history(objective_id,status,reason,at) values(${id},${s},${r},${at})`}
 private map(r:Row,history:Objective['history']):Objective{return{id:r.objective_id,principalId:r.principal_id,...(r.parent_objective_id?{parentObjectiveId:r.parent_objective_id}:{}),statement:r.statement,origin:r.origin,status:r.status,successCriteria:r.success_criteria,childObjectiveIds:r.child_objective_ids,dependencies:r.dependencies,nextActions:r.next_actions,desiredState:r.desired_state??{},...(r.next_evaluation_at?{nextEvaluationAt:new Date(r.next_evaluation_at).toISOString()}:{}),constraints:r.constraints??[],authority:r.authority??{mayReason:true,mayPlan:true,mayPropose:true,mayExecute:false},priority:r.priority,createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString(),...(r.deadline?{deadline:new Date(r.deadline).toISOString()}:{}),provenance:r.provenance,history:history.map(h=>({...h,at:new Date(h.at).toISOString()})),correlationId:r.correlation_id}}
 private emit(type:string,id:string,principalId:string,correlationId:string,payload:unknown){return this.d.events.emit({type:type as never,retentionClass:'AUDIT',privacyClass:'INTERNAL',subject:{kind:'objective',id},actor:{kind:'system',id:'objective-engine'},correlationId,causationId:correlationId,principalId,payload}).then(()=>undefined).catch(()=>undefined)}
}
