import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { isDockerAvailable } from '@jarvis/testkit';
import { setupIt, type ItContext } from './it-harness.ts';
const dockerOk = await isDockerAvailable();
describe.skipIf(!dockerOk)('authoritative backup and restore drill', () => {
  let ctx: ItContext;
  beforeAll(async () => { ctx = await setupIt(); }, 120_000);
  afterAll(async () => { await ctx?.cleanup(); });
  it('restores Kernel state, World Model, memory, invocation, policy and permission rows', async () => {
    const sql = ctx.pg.sql; const at = '2026-09-04T00:00:00Z';
    await sql`insert into projections.state_slices (key,value,version) values ('mode',${JSON.stringify({ mode: 'AMBIENT' })},1)`;
    await sql`insert into atlas.entities (id,type,canonical_name,principal_id) values ('entity-backup','device','Office PC','p')`;
    await sql`insert into mnemosyne.episodes (id,kind,title,summary,occurred_from,occurred_to,confidence,provenance,principal_id) values ('episode-backup','event','Backup','Remember me',${at},${at},1,${JSON.stringify({ source: 'test' })},'p')`;
    await sql`insert into agency.grants (id,principal_id,holder_kind,holder_id,scopes,max_risk_without_live_approval,issued_at) values ('grant-backup','p','principal','p',${['filesystem.read']},'LOW',${at})`;
    await sql`insert into agency.policy_rules (id,version,description,predicate,effect,priority,created_by) values ('policy-backup',1,'backup',${JSON.stringify({ op: 'true' })},'ALLOW',1,'test')`;
    await sql`insert into agency.invocations (invocation_id,proposal_id,capability_id,capability_version,action,state,correlation_id,principal_id,origin_actor,risk_class,input_hash) values ('inv-backup','proposal-backup','capabilities.filesystem','1','read_file','PROPOSED','corr','p',${JSON.stringify({ kind: 'principal', id: 'p' })},'LOW','hash')`;
    const backup = { state: await sql`select * from projections.state_slices`, entities: await sql`select id,type,canonical_name,metadata,privacy_class,principal_id from atlas.entities`, episodes: await sql`select id,kind,title,summary,body_ref,occurred_from,occurred_to,participants,source_event_ids,salience,confidence,provenance,privacy_class,scene_ref,principal_id from mnemosyne.episodes`, grants: await sql`select * from agency.grants`, policies: await sql`select id,version,description,predicate,effect,priority,enabled,created_at,created_by from agency.policy_rules`, invocations: await sql`select invocation_id,proposal_id,capability_id,capability_version,action,state,correlation_id,principal_id,origin_actor,risk_class,input_hash from agency.invocations` };
    await sql`truncate projections.state_slices, atlas.entities, mnemosyne.episodes, agency.invocations, agency.policy_rules, agency.grants cascade`;
    for (const r of backup.state) await sql`insert into projections.state_slices (key,value,version,updated_at) values (${r.key},${JSON.stringify(r.value)},${r.version},${r.updated_at})`;
    for (const r of backup.entities) await sql`insert into atlas.entities (id,type,canonical_name,metadata,privacy_class,principal_id) values (${r.id},${r.type},${r.canonical_name},${JSON.stringify(r.metadata)},${r.privacy_class},${r.principal_id})`;
    for (const r of backup.episodes) await sql`insert into mnemosyne.episodes (id,kind,title,summary,body_ref,occurred_from,occurred_to,participants,source_event_ids,salience,confidence,provenance,privacy_class,scene_ref,principal_id) values (${r.id},${r.kind},${r.title},${r.summary},${r.body_ref},${r.occurred_from},${r.occurred_to},${r.participants},${r.source_event_ids},${r.salience},${r.confidence},${JSON.stringify(r.provenance)},${r.privacy_class},${r.scene_ref},${r.principal_id})`;
    for (const r of backup.grants) await sql`insert into agency.grants (id,principal_id,holder_kind,holder_id,scopes,max_risk_without_live_approval,may_proceed_without_live_approval,resource_constraints,node_constraints,time_windows,version,issued_at,expires_at,revoked_at) values (${r.id},${r.principal_id},${r.holder_kind},${r.holder_id},${r.scopes},${r.max_risk_without_live_approval},${r.may_proceed_without_live_approval},${JSON.stringify(r.resource_constraints)},${r.node_constraints},${JSON.stringify(r.time_windows)},${r.version},${r.issued_at},${r.expires_at},${r.revoked_at})`;
    for (const r of backup.policies) await sql`insert into agency.policy_rules (id,version,description,predicate,effect,priority,enabled,created_at,created_by) values (${r.id},${r.version},${r.description},${JSON.stringify(r.predicate)},${r.effect},${r.priority},${r.enabled},${r.created_at},${r.created_by})`;
    for (const r of backup.invocations) await sql`insert into agency.invocations (invocation_id,proposal_id,capability_id,capability_version,action,state,correlation_id,principal_id,origin_actor,risk_class,input_hash) values (${r.invocation_id},${r.proposal_id},${r.capability_id},${r.capability_version},${r.action},${r.state},${r.correlation_id},${r.principal_id},${JSON.stringify(r.origin_actor)},${r.risk_class},${r.input_hash})`;
    const restored = await sql<{ state: number; world: number; memory: number; invocations: number; policies: number; grants: number }[]>`select (select count(*)::int from projections.state_slices) state,(select count(*)::int from atlas.entities) world,(select count(*)::int from mnemosyne.episodes) memory,(select count(*)::int from agency.invocations) invocations,(select count(*)::int from agency.policy_rules) policies,(select count(*)::int from agency.grants) grants`;
    expect(restored[0]).toEqual({ state: 1, world: 1, memory: 1, invocations: 1, policies: 1, grants: 1 });
  }, 60_000);
});
