import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { randomUUID } from 'node:crypto';
import type { AuthorityToken, Event, Grant, InvocationLifecycle } from '@jarvis/contracts';
import { isDockerAvailable } from '@jarvis/testkit';
import { ApprovalManager, PgGrantStore, PgTokenCache } from '../src/kernel/permission/index.ts';
import { AgencyRecovery, PgInvocationStore, PgResourceLeaseManager } from '../src/kernel/executor/index.ts';
import { ReplayBus, isReplay } from '../src/kernel/event-fabric/replay.ts';
import { setupIt, truncateAll, type ItContext } from './it-harness.ts';

const dockerOk = await isDockerAvailable();
const now = '2026-09-01T00:00:00.000Z';
describe.skipIf(!dockerOk)('durable agency lifecycle (integration)', () => {
  let ctx: ItContext; let store: PgInvocationStore; let grants: PgGrantStore;
  const row = (state: InvocationLifecycle['state'] = 'PROPOSED', suffix = randomUUID()): InvocationLifecycle => ({ invocationId: `inv-${suffix}`, proposalId: `proposal-${suffix}`, capabilityId: 'capabilities.filesystem', capabilityVersion: '1.0.0', action: 'write_file', state, correlationId: `corr-${suffix}`, causationId: `cause-${suffix}`, traceId: `trace-${suffix}`, sessionId: 'session-1', principalId: 'principal-1', originActor: { kind: 'principal', id: 'principal-1' }, riskClass: 'HIGH', inputHash: 'input-hash', proposal: { input: { path: 'x' } }, history: [] });
  const grant = (id = randomUUID()): Grant => ({ id, principalId: 'principal-1', holder: { kind: 'principal', id: 'principal-1' }, scopes: ['filesystem.write'], maxRiskWithoutLiveApproval: 'HIGH', mayProceedWithoutLiveApproval: true, resourceConstraints: [], nodeConstraints: [], timeWindows: [], issuedAt: now, version: 1 });
  beforeAll(async () => { ctx = await setupIt(); await truncateAll(ctx.pg); store = new PgInvocationStore(ctx.pg.sql); grants = new PgGrantStore(ctx.pg.sql); }, 120_000);
  afterAll(async () => { await ctx?.cleanup(); });
  const toApproved = async (initial: InvocationLifecycle) => { await store.create({ ...initial, state: 'PROPOSED' }); await store.transition(initial.invocationId, 'VALIDATED', now, randomUUID()); await store.transition(initial.invocationId, 'POLICY_CHECKED', now, randomUUID()); await store.transition(initial.invocationId, 'APPROVED', now, randomUUID()); };
  const toExecuting = async (initial: InvocationLifecycle) => { await toApproved(initial); const g = grant(); await grants.put(g); await store.patch(initial.invocationId, { grantId: g.id, grantVersion: 1 }); const lease = new PgResourceLeaseManager(ctx.pg.sql, 'crashed-worker', () => new Date(now)); expect(await lease.acquire(`recovery-${initial.invocationId}`, initial.invocationId, 1)).toBe(true); await store.transition(initial.invocationId, 'EXECUTING', now, randomUUID()); await ctx.pg.sql`delete from agency.resource_leases where invocation_id=${initial.invocationId}`; };

  it('reconstructs invocation truth through a fresh store instance', async () => { const initial = row(); await store.create(initial); expect((await new PgInvocationStore(ctx.pg.sql).byProposal(initial.proposalId!))?.traceId).toBe(initial.traceId); });
  it('enforces proposal idempotency in PostgreSQL', async () => { const initial = row(); await store.create(initial); await expect(store.create({ ...row(), proposalId: initial.proposalId })).rejects.toThrow(); });
  it('rejects arbitrary lifecycle jumps in both code and PostgreSQL', async () => { const initial = row(); await store.create(initial); await expect(store.transition(initial.invocationId, 'EXECUTING', now, randomUUID())).rejects.toThrow(/illegal invocation transition/); await expect(ctx.pg.sql`update agency.invocations set state='SUCCEEDED' where invocation_id=${initial.invocationId}`).rejects.toThrow(/illegal invocation transition/); });
  it('persists an awaiting approval across manager restart', async () => { const initial = row(); await store.create(initial); const a = new ApprovalManager(ctx.pg.sql, () => now); const request = await a.request({ invocationId: initial.invocationId, principalId: initial.principalId, capabilityId: initial.capabilityId, capabilityVersion: initial.capabilityVersion, action: initial.action, inputHash: initial.inputHash, riskClass: initial.riskClass, summary: 'exact' }); expect((await new ApprovalManager(ctx.pg.sql, () => now).forInvocation(initial.invocationId))?.nonce).toBe(request.nonce); });
  it('rejects stale approval nonce and version', async () => { const initial = row(); await store.create(initial); const a = new ApprovalManager(ctx.pg.sql, () => now); const request = await a.request({ invocationId: initial.invocationId, principalId: initial.principalId, capabilityId: initial.capabilityId, capabilityVersion: initial.capabilityVersion, action: initial.action, inputHash: initial.inputHash, riskClass: initial.riskClass, summary: 'exact' }); expect(await a.approve({ invocationId: initial.invocationId, operatorId: 'operator', sessionId: 's', authTrustLevel: 'trusted', nonce: `${request.nonce}-stale`, version: request.version! })).toBe(false); });
  it('invalidates approval when arguments change', async () => { const initial = row(); await store.create(initial); const a = new ApprovalManager(ctx.pg.sql, () => now); const binding = { invocationId: initial.invocationId, principalId: initial.principalId, capabilityId: initial.capabilityId, capabilityVersion: initial.capabilityVersion, action: initial.action, inputHash: initial.inputHash, riskClass: initial.riskClass, summary: 'exact' }; await a.request(binding); await expect(a.request({ ...binding, inputHash: 'changed' })).rejects.toThrow(/binding mismatch/); });
  it('persists and atomically consumes authority tokens once', async () => { const initial = row(); await store.create(initial); const g = grant(); await grants.put(g); const token: AuthorityToken = { token: randomUUID(), invocationId: initial.invocationId, grantId: g.id, grantVersion: 1, principalId: initial.principalId, scopes: g.scopes, mode: 'full', issuedAt: now, expiresAt: '2026-09-01T00:02:00.000Z' }; await new PgTokenCache(ctx.pg.sql).put(token); expect(await new PgTokenCache(ctx.pg.sql).consume(token.token, '2026-09-01T00:01:00.000Z')).toMatchObject({ invocationId: initial.invocationId }); expect(await new PgTokenCache(ctx.pg.sql).consume(token.token, '2026-09-01T00:01:00.000Z')).toBeUndefined(); });
  it('allows only one of two workers to acquire execution authority', async () => { const initial = row('APPROVED'); await toApproved(initial); const g = grant(); await grants.put(g); await store.patch(initial.invocationId, { grantId: g.id, grantVersion: 1 }); const one = new PgResourceLeaseManager(ctx.pg.sql, 'worker-1', () => new Date(now)); const two = new PgResourceLeaseManager(ctx.pg.sql, 'worker-2', () => new Date(now)); expect((await Promise.all([one.acquire('resource-race', initial.invocationId), two.acquire('resource-race', initial.invocationId)])).filter(Boolean)).toHaveLength(1); });
  it('permits takeover only after lease expiry', async () => { const first = row('APPROVED'); const second = row('APPROVED'); await toApproved(first); await toApproved(second); const g = grant(); await grants.put(g); await store.patch(first.invocationId, { grantId: g.id, grantVersion: 1 }); await store.patch(second.invocationId, { grantId: g.id, grantVersion: 1 }); const owner = new PgResourceLeaseManager(ctx.pg.sql, 'owner', () => new Date(now)); const contender = new PgResourceLeaseManager(ctx.pg.sql, 'contender', () => new Date('2026-09-01T00:00:31.000Z')); expect(await owner.acquire('takeover', first.invocationId, 1)).toBe(true); expect(await contender.acquire('takeover', second.invocationId, 1)).toBe(true); });
  it('rejects stale worker completion after another terminal outcome', async () => { const initial = row(); await store.create(initial); await store.transition(initial.invocationId, 'REJECTED', now, randomUUID()); await expect(store.transition(initial.invocationId, 'COMPLETED', now, randomUUID())).rejects.toThrow(); });
  it('repeated event replay reaches projectors but never execution authority', async () => { const replay = new ReplayBus(); let projections = 0; const executions = 0; replay.registerProjector('audit', async (event) => { expect(isReplay(event)).toBe(true); projections++; }); const event = { id: randomUUID(), type: 'jarvis.agency.invocation.started', schemaVersion: 1, recordedAt: now, retentionClass: 'AUDIT', privacyClass: 'INTERNAL', source: { component: 'capability-executor', instanceId: 'i', nodeId: 'n' }, subject: { kind: 'invocation', id: 'x' }, actor: { kind: 'system', id: 'executor' }, correlationId: 'c', causationId: 'x', principalId: 'principal-1', payload: { invocationId: 'x' } } as unknown as Event; await replay.feed(event); await replay.feed(event); expect({ projections, executions }).toEqual({ projections: 2, executions: 0 }); });
  it('classifies an expired in-flight effect without re-executing it', async () => { const initial = row('EXECUTING'); await toExecuting(initial); const recovery = new AgencyRecovery(ctx.pg.sql, store, { emit: async () => randomUUID() }, () => '2026-09-01T00:10:00.000Z'); expect(await recovery.recoverExpiredLeases()).toBeGreaterThan(0); expect((await store.get(initial.invocationId))?.state).toBe('UNVERIFIED'); });
  it('continues durable rollback state after restart when pre-state exists', async () => { const initial = row('EXECUTING'); await toExecuting(initial); await store.patch(initial.invocationId, { recoveryState: { content: 'before' } }); const recovery = new AgencyRecovery(ctx.pg.sql, store, { emit: async () => randomUUID() }, () => '2026-09-01T00:10:00.000Z'); await recovery.recoverExpiredLeases(); expect((await store.get(initial.invocationId))?.state).toBe('ROLLBACK_PENDING'); });
  it('does not depend on Redis for invocation, approval, grant, or token truth', async () => { const counts = await ctx.pg.sql<{ invocations: number; approvals: number; grants: number; tokens: number }[]>`select (select count(*)::int from agency.invocations) invocations, (select count(*)::int from agency.approvals) approvals, (select count(*)::int from agency.grants) grants, (select count(*)::int from agency.authority_tokens) tokens`; expect(counts[0]).toMatchObject({ invocations: expect.any(Number), approvals: expect.any(Number), grants: expect.any(Number), tokens: expect.any(Number) }); });
});
