import { readFileSync } from 'node:fs'; import { resolve } from 'node:path'; import { describe, expect, it } from 'vitest';
import { execFileSync } from 'node:child_process';
describe('agency boundary sweep', () => {
  it('keeps adapter imports out of Kernel source', () => { const source = readFileSync(resolve('apps/core/src/kernel/executor/executor.ts'), 'utf8'); expect(source).not.toMatch(/capabilities\//); });
  it('keeps raw input out of the invocation schema', () => { const migration = readFileSync(resolve('packages/persistence/src/migrations/0008_agency.sql'), 'utf8'); const table = migration.match(/create table agency\.invocations \(([\s\S]*?)\n\);/)?.[1] ?? ''; expect(table).toContain('input_hash'); expect(table).not.toMatch(/\binput\s/); });
  it('keeps secret material out of credential grant persistence', () => { const migration = readFileSync(resolve('packages/persistence/src/migrations/0008_agency.sql'), 'utf8'); const table = migration.match(/create table agency\.credential_grants \(([\s\S]*?)\n\);/)?.[1] ?? ''; expect(table).not.toMatch(/secret|token|material/); });
  it('prevents desktop and agents from importing adapters or the Adapter Host', () => { const files = execFileSync('rg', ['--files', 'apps/desktop', 'agents'], { encoding: 'utf8' }).trim().split(/\r?\n/).filter((file) => /\.(?:ts|tsx|js|mjs)$/.test(file)); const source = files.map((file) => readFileSync(resolve(file), 'utf8')).join('\n'); expect(source).not.toMatch(/@jarvis\/adapter-host|capabilities\//); });
  it('keeps the Adapter Host invocation seam owned by the Executor subsystem', () => { const files = execFileSync('rg', ['-l', '@jarvis/adapter-host', 'apps'], { encoding: 'utf8' }).trim().split(/\r?\n/).map((file) => file.replaceAll('\\', '/')).filter((file) => /\.(?:ts|tsx|js|mjs)$/.test(file) && !file.endsWith('boundary-sweep.test.ts') && !file.endsWith('kernel.ts')); expect(files).toEqual(['apps/core/src/kernel/executor/hosted-adapter.ts']); });
});
