import { describe,expect,it } from 'vitest';import type{SessionAccessCredential}from'@jarvis/contracts';import{FakeClock}from'../../runtime/clock.ts';import{SessionCredentialManager,type AccessCredentialStore}from'./access-credentials.ts';
class Store implements AccessCredentialStore{rows=new Map<string,SessionAccessCredential&{secretHash:string}>();live={sessionActive:true,identityActive:true,principalActive:true,nodeActive:true};async insert(r:SessionAccessCredential&{secretHash:string}){this.rows.set(r.secretHash,r)}async find(h:string){return this.rows.get(h)??null}async revokeCredential(id:string,at:string){for(const r of this.rows.values())if(r.id===id)r.revokedAt=at}async revokeSession(id:string,at:string){for(const r of this.rows.values())if(r.sessionId===id)r.revokedAt=at}async revokeIdentity(id:string,at:string){for(const r of this.rows.values())if(r.identityId===id)r.revokedAt=at}async revokeNode(id:string,at:string){for(const r of this.rows.values())if(r.nodeId===id)r.revokedAt=at}async validity(){return this.live}}
let seq=0;const ids={ulid:()=>`id-${++seq}`};const input={identityId:'identity',principalId:'principal',sessionId:'session',nodeId:'node',scopes:['desktop.read','desktop.write'],authStrength:'strong' as const};
it('requires recent strong authentication for approvals even while the read credential remains valid',async()=>{
  const store=new Store(),clock=new FakeClock(0),manager=new SessionCredentialManager({store,clock,ids});
  const old=await manager.issue(input);clock.advance(5*60_000+1);
  const binding={nodeId:'node',sessionId:'session',scopes:['desktop.write'],minimumStrength:'strong' as const,recentWithinMs:5*60_000};
  expect(await manager.authenticate(`Bearer ${old.accessToken}`,{nodeId:'node',sessionId:'session',scopes:['desktop.read']})).not.toBeNull();
  expect(await manager.authenticate(`Bearer ${old.accessToken}`,binding)).toBeNull();
  const fresh=await manager.issue(input);
  expect(await manager.authenticate(`Bearer ${fresh.accessToken}`,binding)).not.toBeNull();
});
describe('session-bound access credentials',()=>{it('binds token to node session and scope and expires it',async()=>{const store=new Store(),clock=new FakeClock(0),m=new SessionCredentialManager({store,clock,ids,ttlMs:1000});const t=await m.issue(input);expect(await m.authenticate(`Bearer ${t.accessToken}`,{nodeId:'node',sessionId:'session',scopes:['desktop.write'],minimumStrength:'strong'})).toMatchObject({principalId:'principal',sessionId:'session'});expect(await m.authenticate(`Bearer ${t.accessToken}`,{nodeId:'wrong',sessionId:'session',scopes:[]})).toBeNull();expect(await m.authenticate(`Bearer ${t.accessToken}`,{nodeId:'node',sessionId:'wrong',scopes:[]})).toBeNull();expect(await m.authenticate(`Bearer ${t.accessToken}`,{nodeId:'node',scopes:['admin']})).toBeNull();clock.advance(1001);expect(await m.authenticate(`Bearer ${t.accessToken}`,{nodeId:'node',scopes:[]})).toBeNull()});it('rejects stolen token and replay after concurrent logout',async()=>{const store=new Store(),clock=new FakeClock(0),m=new SessionCredentialManager({store,clock,ids});const t=await m.issue(input);await Promise.all([store.revokeSession('session',clock.nowIso()),store.revokeSession('session',clock.nowIso())]);expect(await m.authenticate(`Bearer ${t.accessToken}`,{nodeId:'node',scopes:[]})).toBeNull()});it('propagates identity and node revocation',async()=>{for(const key of ['identityActive','nodeActive'] as const){const store=new Store(),m=new SessionCredentialManager({store,clock:new FakeClock(0),ids});const t=await m.issue(input);store.live[key]=false;expect(await m.authenticate(`Bearer ${t.accessToken}`,{nodeId:'node',scopes:[]})).toBeNull()}});it('rotates atomically from the caller perspective',async()=>{const store=new Store(),m=new SessionCredentialManager({store,clock:new FakeClock(0),ids});const old=await m.issue(input);const next=await m.rotate(`Bearer ${old.accessToken}`,{nodeId:'node',sessionId:'session',scopes:[]});expect(next?.credential.generation).toBe(2);expect(await m.authenticate(`Bearer ${old.accessToken}`,{nodeId:'node',scopes:[]})).toBeNull();expect(await m.authenticate(`Bearer ${next!.accessToken}`,{nodeId:'node',scopes:[]})).not.toBeNull()})});
