/// <reference lib="dom" />
import { VisionPipeline } from './pipeline.ts';import { MediaPipeHandTracker } from './mediapipe-tracker.ts';import { VisionKernelClient } from './kernel-client.ts';import { collectBrowserScreenContext } from './screen-context.ts';
const video=document.querySelector<HTMLVideoElement>('#camera')!,status=document.querySelector<HTMLElement>('#status')!;
const params=new URLSearchParams(location.search),core=params.get('core')??'http://127.0.0.1:7420',credential=params.get('credential')??'dev-bootstrap-secret',principal=params.get('principal')??'principal-operator',node=params.get('node')??'local-server',model=params.get('model')??'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task';
history.replaceState({},'',location.pathname);const client=new VisionKernelClient(core,credential,node),pipeline=new VisionPipeline({nodeId:node,principalId:principal,cameraId:'default',model:'MediaPipe Hand Landmarker',calibration:{camera:{x:0,y:0,width:1,height:1},monitorId:'primary',monitor:{x:0,y:0,width:screen.availWidth,height:screen.availHeight},mirrorX:true,quality:.75}});let running=true,lastScreen=0,busy=false;
async function start(){try{const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:60}},audio:false});video.srcObject=stream;const tracker=await MediaPipeHandTracker.create(model);client.publish({commandId:crypto.randomUUID(),nodeId:node,principalId:principal,signal:{type:'camera.restored',cameraId:stream.getVideoTracks()[0]?.label??'default',observedAt:new Date().toISOString()}});status.textContent='LOCAL CAMERA READY — frames remain on this device';
  const loop=async(now:number)=>{if(!running)return;if(busy){pipeline.addDroppedFrame();requestAnimationFrame(loop);return}busy=true;try{const result=await tracker.track(video,now);for(const command of pipeline.process(result))client.publish(command);/* HandLandmarker is not a person detector: never infer presence or absence from hands. */if(now-lastScreen>1000){lastScreen=now;client.publish({commandId:crypto.randomUUID(),nodeId:node,principalId:principal,signal:{type:'screen-context',context:collectBrowserScreenContext()}})}}catch(error){status.textContent=`VISION DEGRADED: ${error instanceof Error?error.message:String(error)}`}finally{busy=false;requestAnimationFrame(loop)}};requestAnimationFrame(loop);
  stream.getVideoTracks()[0]?.addEventListener('ended',()=>{running=false;client.publish(pipeline.cameraLost(new Date().toISOString()));status.textContent='CAMERA LOST — interactions released'});
 }catch(error){client.publish(pipeline.cameraLost(new Date().toISOString()));status.textContent=`CAMERA UNAVAILABLE: ${error instanceof Error?error.message:String(error)}`}}
void start();
