/// <reference lib="dom" />
import {VisionPipeline} from './pipeline.ts';
import {MediaPipeHandTracker} from './mediapipe-tracker.ts';
import {VisionKernelClient} from './kernel-client.ts';
import {collectBrowserScreenContext} from './screen-context.ts';
import {VisionQualification,type Trial} from './qualification.ts';
const video=document.querySelector<HTMLVideoElement>('#camera')!,status=document.querySelector<HTMLElement>('#status')!,devices=document.querySelector<HTMLSelectElement>('#devices')!;
const params=new URLSearchParams(location.search),core=params.get('core')??'http://127.0.0.1:7420',credential=params.get('credential')??'dev-bootstrap-secret',principal=params.get('principal')??'principal-operator',node=params.get('node')??'local-server';
history.replaceState({},'',location.pathname);
const client=new VisionKernelClient(core,credential,node),qualification=new VisionQualification();
let stream:MediaStream|undefined,tracker:MediaPipeHandTracker|undefined,pipeline:VisionPipeline|undefined,generation=0,lastVideo=-1,lastScreen=0,trialStart:number|undefined,trialKind:Trial|undefined;
const value=(id:string)=>Number((document.getElementById(id) as HTMLInputElement).value);
function stop(){generation++;for(const track of stream?.getTracks()??[])track.stop();stream=undefined;tracker?.close();tracker=undefined;if(pipeline)client.publish(pipeline.cameraLost(new Date().toISOString()));video.srcObject=null;status.textContent='Camera stopped. No frames are stored.';}
async function listDevices(){const selected=stream?.getVideoTracks()[0]?.getSettings().deviceId??devices.value;const list=await navigator.mediaDevices.enumerateDevices();devices.replaceChildren(...list.filter(d=>d.kind==='videoinput').map((d,i)=>new Option(d.label||`Camera ${i+1}`,d.deviceId)));if(Array.from(devices.options).some(option=>option.value===selected))devices.value=selected;}
async function start(){stop();const current=generation;try{
 const monitorId=document.querySelector<HTMLInputElement>('#monitor')!.value.trim(),width=value('width'),height=value('height'),x=value('x'),y=value('y');if(!monitorId||![x,y,width,height].every(Number.isFinite)||width<=0||height<=0)throw new Error('invalid calibration');
 pipeline=new VisionPipeline({nodeId:node,principalId:principal,cameraId:devices.value||'default',model:'MediaPipe Hand Landmarker 0.10.35',droppedObservations:()=>client.droppedObservations(),calibration:{camera:{x:0,y:0,width:1,height:1},monitorId,monitor:{x,y,width,height},mirrorX:true,quality:.75}});
 const opened=await navigator.mediaDevices.getUserMedia({video:{...(devices.value?{deviceId:{exact:devices.value}}:{}),width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:30}},audio:false});if(current!==generation){opened.getTracks().forEach(t=>t.stop());return;}stream=opened;video.srcObject=stream;await video.play();
 const loaded=await MediaPipeHandTracker.create();if(current!==generation){loaded.close();return;}tracker=loaded;await listDevices();lastVideo=-1;
 stream.getVideoTracks()[0]?.addEventListener('ended',()=>{if(current===generation){stop();status.textContent='Device lost. Interactions released. Reconnect and select Start.';}});
 client.publish({commandId:crypto.randomUUID(),nodeId:node,principalId:principal,signal:{type:'camera.restored',cameraId:devices.value||'default',observedAt:new Date().toISOString()}});status.textContent='LOCAL CAMERA READY. Mapping is unqualified until physical trials. Frames remain local.';
 const loop=async(now:number)=>{if(current!==generation||!tracker||!pipeline)return;try{if(video.readyState>=2&&video.currentTime!==lastVideo){lastVideo=video.currentTime;const result=await tracker.track(video,now);const commands=pipeline.process(result);for(const command of commands){client.publish(command);if(command.signal.type==='air-touch'&&trialStart!==undefined&&trialKind&&((trialKind==='pinch'&&command.signal.frame.phase==='pinch-start')||(trialKind==='swipe'&&command.signal.frame.phase==='swipe')||(trialKind==='loss'&&command.signal.frame.phase==='lost'))){qualification.trial(trialKind,true,performance.now()-trialStart);trialStart=undefined;trialKind=undefined;}}const first=commands.find(c=>c.signal.type==='air-touch');qualification.sample(result.inferenceLatencyMs,first?.signal.type==='air-touch'?first.signal.frame.point:undefined);if(now-lastScreen>1000){lastScreen=now;client.publish({commandId:crypto.randomUUID(),nodeId:node,principalId:principal,signal:{type:'screen-context',context:collectBrowserScreenContext()}});client.publish(pipeline.runtimeDiagnostics(result));}}}catch{status.textContent='VISION DEGRADED. Stop and restart the selected device.';}if(current===generation)requestAnimationFrame(loop);};requestAnimationFrame(loop);
 }catch{if(current===generation){stop();status.textContent='Camera or pinned local runtime unavailable. Check device permissions and run vision:assets.';}}}
document.querySelector('#start')!.addEventListener('click',()=>void start());document.querySelector('#stop')!.addEventListener('click',stop);
document.querySelector('#begin')!.addEventListener('click',()=>{qualification.start(performance.now());status.textContent='Recording derived measurements. Hold a stationary point for stability; record failures as well as successes.';});
for(const button of Array.from(document.querySelectorAll<HTMLButtonElement>('[data-trial]')))button.addEventListener('click',()=>{trialKind=button.dataset.trial as Trial;trialStart=performance.now();status.textContent=`Perform ${trialKind}. Timing includes your response to this button; it is not pure sensor onset latency.`;});
document.querySelector('#fail')!.addEventListener('click',()=>{if(trialKind)qualification.trial(trialKind,false);trialKind=undefined;trialStart=undefined;});
document.querySelector('#false')!.addEventListener('click',()=>qualification.trial('false-gesture',false));document.querySelector('#clean')!.addEventListener('click',()=>qualification.trial('false-gesture',true));
document.querySelector('#export')!.addEventListener('click',()=>{const report=qualification.report(performance.now(),document.querySelector<HTMLInputElement>('#attest')!.checked);const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='vision-qualification.json';link.click();URL.revokeObjectURL(url);});
navigator.mediaDevices.addEventListener('devicechange',()=>void listDevices());window.addEventListener('pagehide',stop);void listDevices().catch(()=>{});
