import { describe, expect, it } from 'vitest';import { calibratePoint, PointSmoother } from '@jarvis/spatial';import { resolveAirTouch, resolveReference, type SemanticScene } from '@jarvis/scene';import { GestureClassifier } from './gesture-classifier.ts';import { VisionPipeline } from './pipeline.ts';import { evaluateSelectedFrame } from './selected-frame-policy.ts';import type { TrackedHand } from './ports.ts';
const hand=(shape:'point'|'open'|'pinch',x=.5):TrackedHand=>{const p=Array.from({length:21},()=>({x:.5,y:.65}));p[0]={x:.5,y:.9};p[9]={x:.5,y:.55};p[8]={x,y:.2};p[6]={x:.5,y:.55};for(const [tip,base] of [[12,10],[16,14],[20,18]] as const){p[tip]=shape==='open'?{x:.5,y:.2}:{x:.5,y:.7};p[base]={x:.5,y:.55}}p[4]=shape==='pinch'?{x:x+.005,y:.205}:{x:.2,y:.5};return{landmarks:p,handedness:'right',confidence:.92}};
describe('local vision pipeline',()=>{
 it('classifies point, pinch/hold, open palm and swipe with hysteresis',()=>{let now=0;const c=new GestureClassifier();expect(c.classify(hand('point'),now)).toBe('point');expect(c.classify(hand('pinch'),now+=10)).toBe('pinch');expect(c.classify(hand('pinch'),now+=500)).toBe('pinch-hold');c.reset();expect(c.classify(hand('open'),now+=10)).toBe('open-palm');c.reset();c.classify(hand('point',.2),now);expect(c.classify(hand('point',.6),now+=100)).toBe('swipe-right')});
 it('smooths jitter and transforms camera coordinates into a selected monitor',()=>{const smoother=new PointSmoother(.5,3);expect(smoother.update({x:10,y:10})).toEqual({x:10,y:10});expect(smoother.update({x:12,y:11})).toEqual({x:10,y:10});expect(smoother.update({x:20,y:10})).toEqual({x:15,y:10});expect(calibratePoint({x:.25,y:.5},{camera:{x:0,y:0,width:1,height:1},monitorId:'two',monitor:{x:1920,y:0,width:2560,height:1440},mirrorX:true,quality:.9})).toEqual({monitorId:'two',point:{x:3840,y:720},confidence:.9})});
 it('emits pointing/pinch frames and safely releases lost tracking',()=>{let now=0;const pipeline=new VisionPipeline({nodeId:'OFFICE-PC',principalId:'p',cameraId:'cam',model:'test',now:()=>now,calibration:{camera:{x:0,y:0,width:1,height:1},monitorId:'primary',monitor:{x:0,y:0,width:1920,height:1080},mirrorX:false,quality:1}});const result={hands:[hand('point')],personPresent:true,inferenceLatencyMs:8,capturedAt:'2026-01-01T00:00:00Z'};expect(pipeline.process(result)[0]?.signal.type).toBe('air-touch');pipeline.process({...result,hands:[hand('pinch')]});now=250;expect(pipeline.process({...result,hands:[]}) ).toHaveLength(1);expect(pipeline.cameraLost(result.capturedAt).signal.type).toBe('camera.lost')});
 it('magnetically acquires top targets and releases on tracking loss',()=>{const targets=[{objectId:'low',centre:{x:100,y:100},radius:50,zIndex:1},{objectId:'top',centre:{x:100,y:100},radius:50,zIndex:3}];expect(resolveAirTouch({phase:'pinch-start',monitorId:'primary',point:{x:100,y:100},confidence:.9,observedAt:''},targets)).toMatchObject({targetId:'top',action:'focus',acquired:true});expect(resolveAirTouch({phase:'lost',monitorId:'primary',confidence:0,observedAt:''},targets).tracking).toBe('lost')});
 it('keeps ambiguous multimodal references ambiguous',()=>{const scene={id:'s',principalId:'p',version:1,presentation:'DORMANT',monitors:[],objects:[],updatedAt:''} as SemanticScene;expect(resolveReference(scene,{utterance:"what's that?",selectedIds:[],recentIds:[],now:''}).requiresClarification).toBe(true);expect(resolveReference(scene,{utterance:"what's that?",selectedIds:[],recentIds:[],screenRegion:{monitorId:'two',application:'terminal',resourceRef:'screen:error-region',confidence:.88},now:''})).toMatchObject({objectIds:['screen:error-region'],requiresClarification:false})});
 it('fails closed for semantic vision privacy and missing approval',()=>{const base={requestId:'r',principalId:'p',source:'screen' as const,region:{x:0,y:0,width:10,height:10},privacyClass:'SENSITIVE' as const,imageRef:'local-object://frame/1',purpose:'diagnose'};expect(evaluateSelectedFrame(base)).toMatchObject({allowed:false,requiresApproval:true});expect(evaluateSelectedFrame({...base,privacyClass:'RESTRICTED'},'approval')).toMatchObject({allowed:false});expect(evaluateSelectedFrame(base,'approval-1')).toMatchObject({allowed:true})});
});
