import type { ModelHealth, ModelRegistration, ModelRequest, ModelResponse } from '@jarvis/contracts';
import type { ProviderAdapter } from '../provider.ts';
import { httpError, parseOutput, prompt, response, type Fetch } from './shared.ts';
export class AnthropicAdapter implements ProviderAdapter {
  readonly provider = 'anthropic';
  constructor(private readonly apiKey: string, private readonly baseUrl = 'https://api.anthropic.com/v1', private readonly fetcher: Fetch = fetch) {}
  async generate(model: ModelRegistration, request: ModelRequest, signal: AbortSignal): Promise<ModelResponse> { const started = Date.now(); const res = await this.fetcher(`${this.baseUrl}/messages`, { method: 'POST', signal, headers: { 'content-type': 'application/json', 'x-api-key': this.apiKey, 'anthropic-version': '2023-06-01' }, body: JSON.stringify({ model: model.id, max_tokens: request.budget.maxOutput, system: 'Return only valid JSON matching the requested JARVIS proposal contract.', messages: [{ role: 'user', content: prompt(request) }] }) }); if (!res.ok) throw httpError(this.provider, res.status, await res.text()); const body = await res.json() as { content?: Array<{ type: string; text?: string }>; usage?: { input_tokens?: number; output_tokens?: number } }; return response(model, parseOutput(body.content?.find((x) => x.type === 'text')?.text), body.usage?.input_tokens ?? request.budget.contextUnits, body.usage?.output_tokens ?? 0, Date.now() - started); }
  async health(model: ModelRegistration, signal: AbortSignal): Promise<ModelHealth> { const started = Date.now(); try { const res = await this.fetcher(`${this.baseUrl}/models`, { signal, headers: { 'x-api-key': this.apiKey, 'anthropic-version': '2023-06-01' } }); return { modelId: model.id, provider: this.provider, status: res.ok ? 'healthy' : 'offline', checkedAt: new Date().toISOString(), latencyMs: Date.now() - started, ...(!res.ok ? { detail: `HTTP ${res.status}` } : {}) }; } catch (e) { return { modelId: model.id, provider: this.provider, status: 'offline', checkedAt: new Date().toISOString(), detail: e instanceof Error ? e.message : String(e) }; } }
}
