import { describe, expect, it } from 'vitest';
import { z } from 'zod';
import { eventSchema } from '@jarvis/validation';
import type { AdapterJob, WorkerReply } from '../../apps/adapter-host/src/ipc.ts';
import type { AgentResult, ApprovalRequest, AuthorityToken, Capability, ModelRequest, NodeDescriptor } from '@jarvis/contracts';
import type { SemanticScene } from '@jarvis/scene';
import { LEGAL_INVOCATION_TRANSITIONS } from '@jarvis/contracts';

describe('versioned cross-boundary contracts', () => {
  it('accepts a canonical event envelope and rejects a malformed one', () => { const event = { id: '01ARZ3NDEKTSV4RRFFQ69G5FAV', type: 'jarvis.kernel.health.transitioned', schemaVersion: 1, retentionClass: 'OPERATIONAL', time: '2026-09-04T00:00:00.000Z', recordedAt: '2026-09-04T00:00:00.000Z', source: { node: 'core', component: 'health' }, subject: { kind: 'subsystem', id: 'db' }, actor: { kind: 'system', id: 'health' }, provenance: { method: 'system', producedBy: 'health', producedOn: 'core', producedAt: '2026-09-04T00:00:00.000Z', correlationId: 'c', derivedFromUntrusted: false }, causationId: 'none', correlationId: 'c', principalId: 'system', privacyClass: 'INTERNAL', payload: {} }; expect(eventSchema.safeParse(event).success).toBe(true); expect(eventSchema.safeParse({ ...event, source: {} }).success).toBe(false); });
  it('locks the node protocol identity and trust advertisement', () => { const node: NodeDescriptor = { nodeId: 'phone', nodeType: 'mobile', protocolVersion: '1.0', sensors: ['microphone'], capabilities: [], surfaces: ['screen'], requestedTrustTier: 'owned-mobile', attributes: { owner: 'p' } }; expect(node.protocolVersion).toBe('1.0'); expect(node.requestedTrustTier).not.toBe('kernel-local'); });
  it('requires capability execution and verification declarations', () => { const capability = { id: 'capabilities.test', version: '1.0.0', actions: [{ name: 'act', inputSchema: {}, outputSchema: {}, riskClass: 'LOW', reversible: false, simulatable: false, sideEffects: [], verify: 'read', verificationStrategy: { kind: 'adapter', adapterRef: 'read' }, timeoutMs: 1000 }], requiredScopes: [], provider: 'test', description: 'test', executionEnvironment: 'worker', trustTierMin: 'untrusted-node', auditPolicy: { hashInput: true, recordOutput: 'summary' }, privacyRequirements: { maxContentPrivacyClass: 'INTERNAL' } } satisfies Capability; expect(capability.actions[0].verificationStrategy).toBeDefined(); });
  it('binds approval to immutable invocation facts', () => { const approval = { id: 'a', invocationId: 'i', principalId: 'p', capabilityId: 'c', capabilityVersion: '1', action: 'x', inputHash: 'h', riskClass: 'HIGH', summary: 's', state: 'pending', requestedAt: '2026-09-04T00:00:00Z', expiresAt: '2026-09-04T00:01:00Z', nonce: 'n', version: 1, requiredAuthorisations: 1, receivedAuthorisations: 0 } satisfies ApprovalRequest; expect(Object.values(approval).every((value) => value !== undefined)).toBe(true); });
  it('binds permission tokens to principal, invocation, grant version, mode and expiry', () => { const token = { token: 'secret', invocationId: 'i', grantId: 'g', grantVersion: 2, principalId: 'p', scopes: ['x'], mode: 'full', issuedAt: '2026-09-04T00:00:00Z', expiresAt: '2026-09-04T00:01:00Z' } satisfies AuthorityToken; expect(token.grantVersion).toBe(2); });
  it('keeps Model Gateway requests provider-neutral and budgeted', () => { const request = { task: 'reason', capabilities: ['json'], input: { instruction: 'x', context: {} as never, constraints: [] }, budget: { contextUnits: 10, maxOutput: 5 }, locality: 'prefer-local', correlationId: 'c', principalId: 'p' } satisfies ModelRequest; expect(request).not.toHaveProperty('openai'); expect(request.budget.contextUnits).toBe(10); });
  it('requires bounded agent results containing proposals rather than effects', () => { const result = { jobId: 'j', agentId: 'forge', principalId: 'p', correlationId: 'c', status: 'completed', proposals: [], evidence: [], startedAt: '2026-09-04T00:00:00Z', finishedAt: '2026-09-04T00:00:01Z' } satisfies AgentResult; expect(result.proposals).toEqual([]); });
  it('transports semantic scenes with version and principal ownership', () => { const scene = { id: 's', principalId: 'p', version: 1, presentation: 'DORMANT', monitors: [], objects: [], updatedAt: '2026-09-04T00:00:00Z' } satisfies SemanticScene; expect(scene).toMatchObject({ principalId: 'p', version: 1 }); });
  it('keeps SDK and Kernel boundary manifest-shaped', () => { const schema = z.object({ id: z.string().startsWith('capabilities.'), version: z.string(), actions: z.array(z.object({ name: z.string(), verify: z.string() })) }); expect(schema.safeParse({ id: 'capabilities.x', version: '1', actions: [{ name: 'x', verify: 'read' }] }).success).toBe(true); });
  it('locks Adapter Host jobs to invocation, credential handle, version and timeout', () => { const job = { invocationId: 'i', capabilityId: 'c', version: '1', action: 'x', input: {}, handle: { handleId: 'h', invocationId: 'i', scope: { capabilityId: 'c', action: 'x', resourceRef: 'r' }, mode: 'full', expiresAt: '2026-09-04T00:01:00Z', kind: 'none' }, mode: 'full', timeoutMs: 1000, riskClass: 'LOW', executionEnvironment: 'worker', moduleUrl: 'file:///x' } satisfies AdapterJob; const reply: WorkerReply = { ok: false, error: 'crash' }; expect(job.handle.invocationId).toBe(job.invocationId); expect(reply.ok).toBe(false); expect(LEGAL_INVOCATION_TRANSITIONS.EXECUTING).not.toContain('COMPLETED'); });
});
