import type { RegisteredNode } from '@jarvis/contracts';
import type { Sql } from '@jarvis/persistence';
export interface NodeStore {
  get(id:string):Promise<RegisteredNode|null>; put(node:RegisteredNode):Promise<void>;
  consumeEnrollment(hash:string,at:string):Promise<{principalId:string;trustCeiling:RegisteredNode['trustTier']}|null>;
  createEnrollment(hash:string,principalId:string,trustCeiling:RegisteredNode['trustTier'],expiresAt:string):Promise<void>;
}
export class PgNodeStore implements NodeStore {
 constructor(private sql:Sql){}
 async get(id:string){const rows=await this.sql<any[]>`select * from nodes.registry where node_id=${id}`;const r=rows[0];return r?{nodeId:r.node_id,identityId:r.identity_id,principalId:r.principal_id,nodeType:r.node_type,trustTier:r.trust_tier,capabilities:r.capabilities,sensors:r.sensors,outputs:r.outputs,...(r.location?{location:r.location}:{}),softwareVersion:r.software_version,protocolVersion:r.protocol_version,publicKeyFingerprint:r.public_key_fingerprint,...(r.previous_key_fingerprint?{previousKeyFingerprint:r.previous_key_fingerprint}:{}),...(r.previous_key_expires_at?{previousKeyExpiresAt:new Date(r.previous_key_expires_at).toISOString()}:{}),status:r.status,enrolledAt:new Date(r.enrolled_at).toISOString(),...(r.last_seen_at?{lastSeenAt:new Date(r.last_seen_at).toISOString()}:{}),health:r.health,version:r.version,...(r.revoked_at?{revokedAt:new Date(r.revoked_at).toISOString()}:{})}:null}
 async put(n:RegisteredNode){await this.sql`insert into nodes.registry(node_id,identity_id,principal_id,node_type,trust_tier,capabilities,sensors,outputs,location,software_version,protocol_version,public_key_fingerprint,previous_key_fingerprint,previous_key_expires_at,status,enrolled_at,last_seen_at,health,version,revoked_at) values(${n.nodeId},${n.identityId},${n.principalId},${n.nodeType},${n.trustTier},${n.capabilities},${n.sensors},${n.outputs},${n.location??null},${n.softwareVersion},${n.protocolVersion},${n.publicKeyFingerprint},${n.previousKeyFingerprint??null},${n.previousKeyExpiresAt??null},${n.status},${n.enrolledAt},${n.lastSeenAt??null},${JSON.stringify(n.health)},${n.version},${n.revokedAt??null}) on conflict(node_id) do update set capabilities=excluded.capabilities,sensors=excluded.sensors,outputs=excluded.outputs,location=excluded.location,software_version=excluded.software_version,public_key_fingerprint=excluded.public_key_fingerprint,previous_key_fingerprint=excluded.previous_key_fingerprint,previous_key_expires_at=excluded.previous_key_expires_at,status=excluded.status,last_seen_at=excluded.last_seen_at,health=excluded.health,version=excluded.version,revoked_at=excluded.revoked_at`;}
 async createEnrollment(hash:string,p:string,t:RegisteredNode['trustTier'],e:string){await this.sql`insert into nodes.enrollment_tokens(token_hash,principal_id,trust_ceiling,expires_at) values(${hash},${p},${t},${e})`;}
 async consumeEnrollment(hash:string,at:string){const rows=await this.sql<any[]>`update nodes.enrollment_tokens set used_at=${at} where token_hash=${hash} and used_at is null and expires_at>${at} returning principal_id,trust_ceiling`;return rows[0]?{principalId:rows[0].principal_id,trustCeiling:rows[0].trust_ceiling}:null}
}
