import { createHash, randomBytes } from 'node:crypto';
import type { NodeDescriptor, NodeTrustTier, RegisteredNode } from '@jarvis/contracts';
import type { Clock } from '../../runtime/clock.ts';import type { IdGen } from '../../runtime/ids.ts';import type { IdentityManager } from '../identity/identity-manager.ts';import type { NodeStore } from './node-store.ts';
import { KeyedMutex } from '../../runtime/mutex.ts';
 const rank:Record<NodeTrustTier,number>={guest:0,'owned-mobile':1,'owned-secure':2,'kernel-local':3};
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export class NodeManager{
 private gate=new KeyedMutex();
 constructor(private d:{store:NodeStore;identity:IdentityManager;clock:Clock;ids:IdGen;credentials?:{revokeNode(id:string,at:string):Promise<void>};heartbeatTimeoutMs?:number}){}
 async createEnrollment(principalId:string,trustCeiling:NodeTrustTier,ttlMs=300000){if(!Number.isInteger(ttlMs)||ttlMs<1||ttlMs>300000)throw new Error('invalid enrollment lifetime');if(trustCeiling==='kernel-local')throw new Error('kernel-local enrollment is reserved for the composition root');const token=randomBytes(32).toString('base64url');await this.d.store.createEnrollment(hash(token),principalId,trustCeiling,new Date(this.d.clock.epochMs()+ttlMs).toISOString());return token}
 async enroll(input:{token:string;descriptor:NodeDescriptor;publicKeyFingerprint:string;outputs?:string[];softwareVersion:string;location?:string}){if(!/^[A-Za-z0-9._:-]{3,128}$/.test(input.descriptor.nodeId)||!/^sha256:[a-f0-9]{64}$/.test(input.publicKeyFingerprint))throw new Error('invalid node identity');if(await this.d.store.get(input.descriptor.nodeId))throw new Error('duplicate enrollment');const grant=await this.d.store.consumeEnrollment(hash(input.token),this.d.clock.nowIso());if(!grant)throw new Error('invalid or consumed enrollment token');const requested=input.descriptor.nodeType==='mobile'&&rank[input.descriptor.requestedTrustTier]>rank['owned-mobile']?'owned-mobile':input.descriptor.requestedTrustTier;const trustTier=rank[requested]<=rank[grant.trustCeiling]?requested:grant.trustCeiling;const identity=await this.d.identity.registerIdentity({kind:'node',principalId:grant.principalId,externalRef:input.descriptor.nodeId,displayName:input.descriptor.nodeId,trust:trustTier==='guest'?'provisional':'trusted'});const node:RegisteredNode={nodeId:input.descriptor.nodeId,identityId:identity.id,principalId:grant.principalId,nodeType:input.descriptor.nodeType,trustTier,capabilities:input.descriptor.capabilities,sensors:input.descriptor.sensors,outputs:input.outputs??input.descriptor.surfaces,softwareVersion:input.softwareVersion,protocolVersion:input.descriptor.protocolVersion,publicKeyFingerprint:input.publicKeyFingerprint,status:'connected',enrolledAt:this.d.clock.nowIso(),lastSeenAt:this.d.clock.nowIso(),health:{},version:1,...(input.location?{location:input.location}:{})};await this.d.store.put(node);return node}
 heartbeat(nodeId:string,fingerprint:string,health:Record<string,unknown>={}){return this.gate.run(nodeId,()=>this.doHeartbeat(nodeId,fingerprint,health))}
 private async doHeartbeat(nodeId:string,fingerprint:string,health:Record<string,unknown>){const n=await this.required(nodeId);if(n.status==='revoked'||n.status==='isolated')throw new Error(`node ${n.status}`);const current=fingerprint===n.publicKeyFingerprint;const overlap=fingerprint===n.previousKeyFingerprint&&!!n.previousKeyExpiresAt&&Date.parse(n.previousKeyExpiresAt)>this.d.clock.epochMs();if(!current&&!overlap)throw new Error('node key mismatch');const next={...n,status:'connected' as const,lastSeenAt:this.d.clock.nowIso(),health,version:n.version+1};await this.d.store.put(next);return next}
 /** Liveness sweep: every connected node whose last heartbeat is older than the
  *  timeout becomes `disconnected`. Driven by the `node.liveness_sweep` Scheduler
  *  routine — without it a departed node would stay `connected` forever
  *  (defect found in the MK.42 RC audit: this method used to `return []`). */
 async sweep(){const cutoff=new Date(this.d.clock.epochMs()-(this.d.heartbeatTimeoutMs??30000)).toISOString();const stale=await this.d.store.listStale(cutoff);const out:RegisteredNode[]=[];for(const candidate of stale){const changed=await this.gate.run(candidate.nodeId,async()=>{const n=await this.required(candidate.nodeId);if(n.status!=='connected'||(n.lastSeenAt&&n.lastSeenAt>=cutoff))return null;const next={...n,status:'disconnected' as const,version:n.version+1};await this.d.store.put(next);return next;});if(changed)out.push(changed)}return out}
 markTimedOut(nodeId:string){return this.gate.run(nodeId,()=>this.doMarkTimedOut(nodeId))}
 private async doMarkTimedOut(nodeId:string){const n=await this.required(nodeId);if(n.status==='revoked'||n.status==='isolated')return n;if(!n.lastSeenAt||this.d.clock.epochMs()-Date.parse(n.lastSeenAt)<(this.d.heartbeatTimeoutMs??30000))return n;const next={...n,status:'disconnected' as const,version:n.version+1};await this.d.store.put(next);return next}
 revoke(nodeId:string,isolate=false){return this.gate.run(nodeId,()=>this.doRevoke(nodeId,isolate))}
 private async doRevoke(nodeId:string,isolate:boolean){const n=await this.required(nodeId);const at=this.d.clock.nowIso();const next={...n,status:(isolate?'isolated':'revoked') as 'isolated'|'revoked',revokedAt:at,version:n.version+1};await this.d.store.put(next);await this.d.credentials?.revokeNode(nodeId,at);return next}
 rotateKey(nodeId:string,oldFingerprint:string,newFingerprint:string,overlapMs=60000){return this.gate.run(nodeId,()=>this.doRotateKey(nodeId,oldFingerprint,newFingerprint,overlapMs))}
 private async doRotateKey(nodeId:string,oldFingerprint:string,newFingerprint:string,overlapMs:number){const n=await this.required(nodeId);if(n.status==='revoked'||n.status==='isolated')throw new Error('node revoked');if(!/^sha256:[a-f0-9]{64}$/.test(newFingerprint)||!Number.isFinite(overlapMs)||overlapMs<0||overlapMs>60000)throw new Error('invalid key rotation');if(n.publicKeyFingerprint!==oldFingerprint)throw new Error('node key mismatch');const next={...n,previousKeyFingerprint:n.publicKeyFingerprint,previousKeyExpiresAt:new Date(this.d.clock.epochMs()+overlapMs).toISOString(),publicKeyFingerprint:newFingerprint,version:n.version+1};await this.d.store.put(next);return next}
 private async required(id:string){const n=await this.d.store.get(id);if(!n)throw new Error('node not enrolled');return n}
}
