import { describe, expect, it } from 'vitest'; import type { MonitorSurface } from '@jarvis/spatial'; import type { SemanticScene } from './types.ts'; import { createSnapshot, reconcileMonitors, restoreScene } from './reducer.ts'; import { resolveReference } from './reference-resolver.ts';
import { resolveAirTouch } from './gesture-resolver.ts';
const monitor = (id: string, x = 0): MonitorSurface => ({ id, label: id, bounds: { x, y: 0, width: 1000, height: 800 }, workArea: { x, y: 0, width: 1000, height: 760 }, scaleFactor: 1, primary: id === 'a', connected: true });
const scene = (): SemanticScene => ({ id: 's', principalId: 'p', version: 1, presentation: 'WORKING', monitors: [monitor('a'), monitor('b', 1000)], updatedAt: '2026-09-03T00:00:00Z', objects: [{ id: 'research', kind: 'research', title: 'Research', semanticRole: 'evidence', monitorId: 'b', position: { x: 1200, y: 100 }, size: { width: 400, height: 300 }, zIndex: 1, state: 'expanded', pinned: false, dismissible: true, resourceRefs: ['doc:1'], updatedAt: '2026-09-03T00:00:00Z', data: {} }] });
describe('semantic scene resilience', () => {
  it('restores valid references and rejects stale scene objects', () => { const s = scene(); const restored = restoreScene(s, createSnapshot(s, 'yesterday'), s.monitors, new Set()); expect(restored.objects).toHaveLength(0); });
  it('moves an object safely when its monitor disconnects', () => { const restored = reconcileMonitors(scene(), [monitor('a')]); expect(restored.objects[0]?.monitorId).toBe('a'); expect(restored.objects[0]!.position.x).toBeLessThanOrEqual(600); });
  it('survives monitor reorder because assignment uses stable ids', () => { const s = scene(); expect(reconcileMonitors(s, [monitor('b', 0), monitor('a', 1000)]).objects[0]?.monitorId).toBe('b'); });
  it('resolves voice plus pointing outside the UI', () => { const s = scene(); const result = resolveReference(s, { utterance: 'expand this', selectedIds: [], recentIds: [], pointing: { kind: 'point', monitorId: 'b', point: { x: 1300, y: 150 }, confidence: .92, observedAt: s.updatedAt }, now: s.updatedAt }); expect(result.objectIds).toEqual(['research']); });
  it('asks for clarification when a spatial reference is stale', () => { expect(resolveReference(scene(), { utterance: 'move that', selectedIds: [], recentIds: [], now: '2026-09-03T00:00:00Z' }).requiresClarification).toBe(true); });
  it('magnetically acquires the highest spatial target for pinch', () => { const result = resolveAirTouch({ phase: 'pinch-start', monitorId: 'a', point: { x: 100, y: 100 }, confidence: .9, observedAt: 'now' }, [{ objectId: 'low', centre: { x: 105, y: 105 }, radius: 30, zIndex: 1 }, { objectId: 'high', centre: { x: 105, y: 105 }, radius: 30, zIndex: 3 }]); expect(result).toMatchObject({ targetId: 'high', acquired: true, action: 'focus' }); });
  it('shows lost tracking without creating an action', () => { expect(resolveAirTouch({ phase: 'lost', monitorId: 'a', confidence: 0, observedAt: 'now' }, [])).toEqual({ acquired: false, tracking: 'lost' }); });
});
